### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by alexankitty** [obsproject/obs-websocket#1000]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0

### obs-websocket Version

5.0.0

### OBS Studio Log URL

https://obsproject.com/logs/uOV7rb1hgbSG5RJa

### Expected Behavior

Websocket should be emitting a SceneItemTransformChanged event when cropping, resizing, or performing other transforms with SceneItems

### Current Behavior

Nothing, the websocket does not appear to emit the expected event, and enabling the debug shows that nothing happens when transforming a sceneitem.

### Steps to Reproduce

1. Go to tools > obs-websocket settings
2. Enable Debug Logging
3. Go to Help > Log Files > Show Current Log
4. Resize a sceneitem
5. Check log for output.

**Comment by tt2468** [comment]
You need to subscribe to the [`EventSubscription::SceneItemTransformChanged`](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#eventsubscriptionsceneitemtransformchanged) intent.
