### ISSUE TITLE
Bug: obs-websocket-compat not compatible with OBS 28.0.1

### ISSUE THREAD

**Issue by iarspider** [obsproject/obs-websocket#1004]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1

### obs-websocket Version

5.0.1

### OBS Studio Log URL

https://obsproject.com/logs/axLYt8YRDbY5qt6w

### Expected Behavior

Compat plugin should be loaded to provide API for old clients

### Current Behavior

---------------------------
Plugin Load Error
---------------------------
The following OBS plugins failed to load:

obs-websocket-compat

Please update or remove these plugins.
---------------------------
OK   
---------------------------

### Steps to Reproduce

Start OBS 28.0.1 after installing obs-websocket-4.9.1-compat-Windows-Installer.exe

**Comment by tt2468** [comment]
Please try to do at least basic research before submitting new issues: https://github.com/obsproject/obs-websocket/releases/tag/4.9.1-compat

**Comment by iarspider** [comment]
Oops, my bad. Thanks!
