### ISSUE TITLE
Feature Request: Scene Item Changed event type

### ISSUE THREAD

**Issue by SaviorXTanren** [obsproject/obs-websocket#1008]
### Feature Request Type

RPC Event

### Requested Feature

A pull over from a previous option available in 4.0 that I don't *think* I've seen so far in 5.0?

https://github.com/obsproject/obs-websocket/issues/48

Add event types SceneItemChanged

"SceneItemChanged"
An item has been changed in the current scene

- "scene-name" (string) : name of scene
- "item-name" (string) : old name of the changed item
- "new-item-name" (string) : old or new name of the changed item if renamed

### Requested Feature Usage Scenario

To be notified when a source name has changed to assist with caching of source information. This is mainly to assist with the fact that scenes with large numbers of groups can cause slow down when trying to query for a specific source embedded inside a group. So we have added a layer of caching in our program to handle this, however we need to be notified when a scene item has changed in order to invalidate parts of the cache.

**Comment by tt2468** [comment]
The event you're looking for is called `InputNameChanged`. Scene items do not have names.
