### ISSUE TITLE
Feature Request: Add the list of all webhook datafields...

### ISSUE THREAD

**Issue by Starmania** [obsproject/obs-websocket#1009]
### Feature Request Type

Other

### Feature Request Type (Other)

Docs

### Requested Feature

Add the full list of datafields that you could send or receive or add a link to explore them on the source code.

### Requested Feature Usage Scenario

When you are developing your client, it's easier to know the list of things that OBS send you, and what could you send to

**Comment by Starmania** [comment]
Ok, just add anchors for [here](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#requests) and [here](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#events)

**Comment by tt2468** [comment]
What do you mean by webhook datafields?

**Comment by Starmania** [comment]
I mean the list of all [Events](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#events)
and [Requests](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#requests)

**Comment by Starmania** [comment]
If in the readme you can add a link to this file explaining that Events and Requests are in this file, it will be more accecible...

**Comment by Starmania** [comment]
On the line where you specify where to find the Protocol, add for example `(`[Events](https://example.com)` and `[Requests](https://example.com)`)`
