### ISSUE TITLE
Bug: SetSceneItemTransform not setting a source's width and height on a successfully made request.

### ISSUE THREAD

**Issue by Web-Mage** [obsproject/obs-websocket#1017]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1

### obs-websocket Version

5.0.1

### OBS Studio Log URL

https://obsproject.com/logs/C9iPV0ZUywGI3sv9

### Expected Behavior

When changing "width" and "height" the scene item should resize to reflect the new changes.

### Current Behavior

The source will not change regardless if I use width/height or sourceWidth/sourceHeight. Tried several combinations of adding or removing items retrieved from the GetSceneItemTransform response. Position will change and crops will change without fail, but not the actual dimensions of the source/scene item.

### Steps to Reproduce

1. Send request for SetSceneItemTransform with a payload with a new width and height integer.

Side Notes:
The target source for the following request was a browser source with a width of 800 and height of 600. No cropping, no bounding box, no scaling.

The log snip below was a third attempt with different settings.

Not sure if related, but the original GetSceneItemTransform returned a boundsHeight and boundsWidth of 0, but when I tried to send the same integer back, I did receive an error of "Error: The field value of `boundsWidth` is below the minimum of `1.000000`"

--- Begin Log Snippet ---
19:43:51.332: {
19:43:51.332:   "d": {
19:43:51.332:     "requestData": {
19:43:51.332:       "sceneItemId": 4,
19:43:51.332:       "sceneItemTransform": {
19:43:51.332:         "alignment": 5,
19:43:51.332:         "boundsAlignment": 0,
19:43:51.332:         "boundsHeight": 400,
19:43:51.332:         "boundsType": "OBS_BOUNDS_NONE",
19:43:51.332:         "boundsWidth": 400,
19:43:51.332:         "cropBottom": 0,
19:43:51.332:         "cropLeft": 0,
19:43:51.332:         "cropRight": 0,
19:43:51.332:         "cropTop": 0,
19:43:51.332:         "height": 400,
19:43:51.332:         "positionX": 0,
19:43:51.332:         "positionY": 0,
19:43:51.332:         "rotation": 0,
19:43:51.332:         "scaleX": 1,
19:43:51.332:         "scaleY": 1,
19:43:51.332:         "sourceHeight": 400,
19:43:51.332:         "sourceWidth": 400,
19:43:51.332:         "width": 400
19:43:51.332:       },
19:43:51.332:       "sceneName": "Scene"
19:43:51.332:     },
19:43:51.332:     "requestId": "3462",
19:43:51.332:     "requestType": "SetSceneItemTransform"
19:43:51.332:   },
19:43:51.332:   "op": 6
19:43:51.332: }
19:43:51.333: [obs-websocket] [debug] [WebSocketServer::onMessage] Outgoing message:
19:43:51.333: {
19:43:51.333:   "d": {
19:43:51.333:     "requestId": "3462",
19:43:51.333:     "requestStatus": {
19:43:51.333:       "code": 100,
19:43:51.333:       "result": true
19:43:51.333:     },
19:43:51.333:     "requestType": "SetSceneItemTransform"
19:43:51.333:   },
19:43:51.333:   "op": 7
19:43:51.333: }
--- End Log Snippet ---

**Comment by SanshooSenshi** [comment]
I use the response from Get Scene Item Transform To set another Item in another scene exactly the same. 
but I got an error : 

REQUEST

{
  "requestType": "GetSceneItemTransform",
  "requestData": {
    "sceneName": "[NS] SPOTIFY",
    "sceneItemId": 9
  }
}
RESPONSE 

{"sceneItemTransform":{"alignment":5,"boundsAlignment":0,"boundsHeight":0,"boundsType":"OBS_BOUNDS_NONE","boundsWidth":0,"cropBottom":0,"cropLeft":0,"cropRight":0,"cropTop":0,"height":225,"positionX":749,"positionY":431,"rotation":0,"scaleX":0.9574999809265137,"scaleY":1,"sourceHeight":225,"sourceWidth":800,"width":766}}


then 

{"requestType":"SetSceneItemTransform","requestData":{"sceneName":"[NS] SPOT TO SB","sceneItemId":2,"sceneItemTransform":{"alignment":5,"boundsAlignment":0,"boundsHeight":0,"boundsType":"OBS_BOUNDS_NONE","boundsWidth":0,"cropBottom":0,"cropLeft":0,"cropRight":0,"cropTop":0,"height":225,"positionX":749,"positionY":431,"rotation":0,"scaleX":0.9574999809265137,"scaleY":1,"sourceHeight":225,"sourceWidth":800,"width":766}}}

RESPONSE

Error: The field value of `boundsWidth` is below the minimum of `1.000000`

**Comment by HappyPlotter** [comment]
According to this https://github.com/obsproject/obs-websocket/blob/265899f76f88a5be74747308fff3d35347ce43c5/src/requesthandler/RequestHandler_SceneItems.cpp#L323

The only changes that can be done are to 
positionX
positionY
rotation
scaleX
scaleY
alignment
boundsAlignment
boundsWidth
boundsHeight
cropLeft
cropRight
cropTop
cropBottom

sourceWidth, sourceHeight, width, height are missing and cannot be changed.

**Comment by ChristopheCVB** [comment]
Two things here:

1. If you want to change only 1 item in the transform, then send that item only
2. `width` and `height` are computed values using respectively `sourceWidth * scaleX` and `sourceHeight * scaleY`

With that, if you want to change the size of a SceneItem, change the scales (`scaleX` and `scaleY`)

**Comment by markschwartzkopf** [comment]
It seems like there should be some documentation on which transform properties are read-only. And/or that the error should be specifically related to attempting to change read-only properties rather than "Error: You have not provided any valid transform changes."

**Comment by tt2468** [comment]
To be clear, the failure in documentation here is that the fields of the `sceneItemTransform` object are simply not documented at all. This has been on my todo list to improve upon. My apologies for the confusion.

**Comment by Urge2Burge** [comment]
> Two things here:
> 
> 1. If you want to change only 1 item in the transform, then send that item only
> 2. `width` and `height` are computed values using respectively `sourceWidth * scaleX` and `sourceHeight * scaleY`
> 
> With that, if you want to change the size of a SceneItem, change the scales (`scaleX` and `scaleY`)

Hi Chris, unfortunately I kinda disagree with that second statement, though I understand what you mean by it.

Although "width" and "height" are computed, in my opinion you should still be able to change the "sourceHeight" and "sourceWidth" properties of a scene item under this command, keeping the "ScaleX" and "ScaleY" the same.  This currently doesnt happen under sceneitemtransform but I hope that if it's possible for these to be updated so that it overrides the "sourceHeight" and "sourceWidth" properties and not through scaling.

The guys in the SAMMI (Used to be called LioranBoard) side of things have been able to change these via a command on their end, although theirs is done through editing the input settings, rather than sceneitemtransform.   

If the width and height pixels can only be done via editing the Input Settings, will there be an inclusion of a "SetInputSettings" command?

**Comment by tt2468** [comment]
Closing this since there are other open issues which encompass this one (missing object documentation)
