### ISSUE TITLE
Docs request: Clarify deprecation alternative

### ISSUE THREAD

**Issue by Rosuav** [obsproject/obs-websocket#1020]
### Feature Request Type

Other

### Feature Request Type (Other)

Explain what SHOULD be done instead of what's discouraged

### Requested Feature

In [GetGroupSceneItemList](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getgroupsceneitemlist), the use of groups is discouraged. It would be helpful to say what is encouraged instead - for instance, is the use of a scene as a source in another scene as broken as groups, or a non-broken alternative?

### Requested Feature Usage Scenario

Someone comes to the docs to look at ways to manipulate groups, sees a scary warning, and currently has no idea what to do instead. A brief docs mention would be an authoritative recommendation, guiding the user to a safer alternative.

**Comment by tt2468** [comment]
Clarified via docs commit

**Comment by Rosuav** [comment]
Thanks! Appreciate it!
