### ISSUE TITLE
Bug: Scenes listed in reverse order

### ISSUE THREAD

**Issue by Rosuav** [obsproject/obs-websocket#1034]
### Operating System Info

Other

### Other OS

Debian Bullseye

### OBS Studio Version

Git

### obs-websocket Version

5.0.1

### OBS Studio Log URL

n/a

### Expected Behavior

Calling GetSceneList returns an array of current scenes in the order that they are shown in the OBS UI.

### Current Behavior

Calling GetSceneList returns the array of scenes in precisely the opposite order.

### Steps to Reproduce

1. Call GetSceneList
2. Observe the order of returned scenes

### Anything else we should know?

OBS WebSocket v4 gives the scenes in the correct order.

**Comment by Miniontoby** [comment]
This also happens at GetInputList and maybe also at other Lists

**Comment by Miniontoby** [comment]
> You could use the `sceneIndex` field to reorder on your side? Not possible for inputs though :/

Look, there are tons of ways to do it client sided and the easiest is to just do `reverse(YOUR_SCENE_LIST_VAR)`

But we want this to be fixed from the base code itself and not client sided...

**Comment by Rosuav** [comment]
Part of the reason this is problematic is that the v4 server returns them in the correct order, so making a client that supports both means special-casing this to reorder them.

Any idea WHY they're being returned backwards? It seems to be being done for all arrays, but maybe that's not correct for scenes??

**Comment by tt2468** [comment]
Remember, 5.x's intention was to *not* try to stick to the behavior norms of 4.x.

5.x returns scenes in the order given to match the behavior of `GetSceneItemList`

**Comment by Rosuav** [comment]
Okay, but this does NOT match the order given in the OBS user interface.

**Comment by cubiclesoft** [comment]
Just ran into this bug myself.  Scene order is in reverse from what the UI shows.  Tag for this issue should be changed to Confirmed Bug.

The earlier suggestion to use `sceneIndex` is not helpful.  The last item in the list in the UI appears first and has an index of 0 in the array and the index increments for each item after that.  The information presented on the Websocket interface should mirror what the UI displays to the user.  I can't think of a scenario where the reverse order from what displays in the UI would ever make sense as default behavior.

**Comment by tt2468** [comment]
Feel free to suggest that this behavior be changed in a future RPC version bump, but for now this behavior is working as intended and is not a bug.

**Comment by Rosuav** [comment]
Okay. Can you please explain the justification for this being intended behaviour, though? You say that it matches GetSceneItemList, but why is *that* in reverse order of the UI? What exactly is correctness being defined as?

**Comment by tt2468** [comment]
As stated above, the intended behavior is to match the ID direction of scene items, where ID 0 is at the bottom of the list in the UI.
