### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by sebionofrei** [obsproject/obs-websocket#1038]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.3

### obs-websocket Version

5.0.1

### OBS Studio Log URL

https://obsproject.com/logs/Owe8VfbHYXOoUeFM

### Expected Behavior

When changing PORT number of websockets, to re-call all external plugins that register for vendor requests via obs_websocket_vendor_register_request

### Current Behavior

It seems to me that when you manually change the WebSocket PORT number, OBS is re-creating the sockets.
Though what I feel is that when websockets are re-created, it "forgets" to re-register external Vendor requests (obs_websocket_vendor_register_request)

### Steps to Reproduce

1. start obs, using a custom plugin that has manually registered custom requests using obs_websocket_vendor_register_request
2. make sure that your vendor request is working
3. change the WS port number to something else
4. test again if your vendor request is working. Currently it is not, it will respond that "we could not find the vendor". But if you close OBS and restart it, it will work
...

**Comment by tt2468** [comment]
I'm unable to reproduce this issue, or find any code that could reasonably cause this kind of bug. The vendor API is effectively an entirely separate part of the plugin, and the `CallVendorRequest` code fetches a globally available reference statelessly, so restarting the WebSocket server does not affect its ability to access the vendor API.
