### ISSUE TITLE
Feature Request: Screenshot save event

### ISSUE THREAD

**Issue by DmitriySalnikov** [obsproject/obs-websocket#1047]
### Feature Request Type

RPC Event

### Requested Feature

Currently, there are only two requests in the API to save screenshots, but there is no event triggered by the user saving a screenshot via the OBS hotkey.

### Requested Feature Usage Scenario

Log or display notifications about saving a screenshot in third-party programs.

For me, this is needed because a couple of people asked me to add this feature to my [OBS Notifier](https://github.com/DmitriySalnikov/OBSNotifier).

**Comment by tt2468** [comment]
Done: https://github.com/obsproject/obs-websocket/commit/8cabe24b7789ee95f7a5abbe3ab15d8d6a73ca61
