### ISSUE TITLE
Feature Request: Event for stream reconnect

### ISSUE THREAD

**Issue by BenediktSeidl** [obsproject/obs-websocket#1050]
### Feature Request Type

RPC Event

### Requested Feature

Receiving a websocket event when the desktop notification "Disconnected. Reconnecting..." and "Reconnection successful" is shown.

### Requested Feature Usage Scenario

When i subscribe to `EventSubscription::Outputs` I see some events, but according to those events the connection is working, although I see some desktop notifications, showing that the stream was disconnected:

```
# start streaming
{"d": {"eventData": {"outputActive": false, "outputState": "OBS_WEBSOCKET_OUTPUT_STARTING"}, "eventIntent": 64, "eventType": "StreamStateChanged"}, "op": 5}
{"d": {"eventData": {"outputActive": true, "outputState": "OBS_WEBSOCKET_OUTPUT_STARTED"}, "eventIntent": 64, "eventType": "StreamStateChanged"}, "op": 5}
# saw desktop notifications here, but no events
# stopped streaming
{"d": {"eventData": {"outputActive": false, "outputState": "OBS_WEBSOCKET_OUTPUT_STOPPING"}, "eventIntent": 64, "eventType": "StreamStateChanged"}, "op": 5}
{"d": {"eventData": {"outputActive": false, "outputState": "OBS_WEBSOCKET_OUTPUT_STOPPED"}, "eventIntent": 64, "eventType": "StreamStateChanged"}, "op": 5}
```

Currently i would have to poll to see if a Stream is in trouble: I can use the `GetStreamStatus` RPC Request and look at the boolean `outputReconnecting`. But if the poll interval is too long (or the reconnecting problem too short), I might miss the state during which the output is reported to be reconnecting, even though some kind of interruption might have happened.

I would like to detect if the stream has been reconnecting independent of the poll duration.

**Comment by tt2468** [comment]
As described by github saying `tt2468 closed this as completed...`, this issue is closed, because the request **has been completed.**

The update will be released with OBS 29.

**Comment by lassos** [comment]
ah ok thanks .-) i didnt know that. right now i am using obs 28.1.2 do you know when obs 29 will be released ?
