### ISSUE TITLE
Feature Request: Document PrivateSettings calls

### ISSUE THREAD

**Issue by JMC-design** [obsproject/obs-websocket#1057]
### Feature Request Type

Other

### Feature Request Type (Other)

documentation

### Requested Feature

document 
 "GetSceneItemPrivateSettings"
"GetSourcePrivateSettings"
"SetSourcePrivateSettings"
"SetSceneItemPrivateSettings"
 as they don't appear in protocol.md but are returned as available requests in getVersion.

### Requested Feature Usage Scenario

implementing obs ws interface.

**Comment by tt2468** [comment]
These requests are intentionally undocumented to discourage usage.
