### ISSUE TITLE
Bug:  4.9.1 not working with obs 28.1.2 as told

### ISSUE THREAD

**Issue by TheApexDevil** [obsproject/obs-websocket#1058]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.x

### obs-websocket Version

Git

### OBS Studio Log URL

4.9.1

### Expected Behavior

well i expected it to work as in the documetation

### Current Behavior

![image](https://user-images.githubusercontent.com/44646723/202854060-fc04bce4-54e6-4ca1-b766-0b3187c08d06.png)
not working

### Steps to Reproduce

1.install obs 28.1.2
2.install websocket 9.4.1
3.open obs
...

**Comment by gxalpha** [comment]
You downloaded the wrong binaries, try the ones from here: https://github.com/obsproject/obs-websocket/releases/tag/4.9.1-compat

**Comment by TheApexDevil** [comment]
> You downloaded the wrong binaries, try the ones from here: https://github.com/obsproject/obs-websocket/releases/tag/4.9.1-compat

tis is what i downloaded so the most have uploaded the wrong build to the wrong repo
