### ISSUE TITLE
Feature Request: Retrieve currently supported streaming services on OBS

### ISSUE THREAD

**Issue by TheLightningStrikes** [obsproject/obs-websocket#1060]
### Feature Request Type

RPC Request

### Requested Feature

RPC Request where you ask OBS which services and presets of those services it currently supports/provides.

### Requested Feature Usage Scenario

Useful when you want to know which streaming services + servers you can connect to.

**Comment by tt2468** [comment]
You can fetch the current OBS services from here: https://obsproject.com/obs2_update/rtmp-services/services.json

**Comment by TheLightningStrikes** [comment]
Sweet, thanks!

**Comment by tt2468** [comment]
Actually, you'll want this URL: https://obsproject.com/obs2_update/rtmp-services/v3/services.json

**Comment by TheLightningStrikes** [comment]
I am using this list now and I notice that servers are missing on it, for example for Twitch. They _are_ listed in OBS however, so I wonder how they get those. Might wait for an update on the services.json.
