### ISSUE TITLE
Feature Request: Re-add support for SetRecordingFolder, SetFileNameFormatting

### ISSUE THREAD

**Issue by acstark92** [obsproject/obs-websocket#1062]
### Feature Request Type

RPC Request

### Requested Feature

obs-websocket version 4.9.1 contained support for setting the folder for saved video recordings, as well as support for setting the filename of said video. As of 5.0.0, this support seems to no longer be available.

### Requested Feature Usage Scenario

As part of an automated test, I want to record my game and save those recordings off to dynamic locations for later validation. I would have a pipeline that calls obs-websocket to set the file location and filename, then start and stop recording.

**Comment by DoubleF3lix** [comment]
I'm proud to report that this works (in `obsws-python`) for `SetFileNameFormatting`:
```py
connection.get_profile_parameter("Output", "FilenameFormatting").parameter_value
connection.set_profile_parameter("Output", "FilenameFormatting", "My File Name")
```

**Comment by hendryman** [comment]
+1 for setting folder names via script. Is there any update on that?

**Comment by minorDeveloper** [comment]
@acstark92, your request for setting filename formatting is possible with a request as shown below:

`{"op": 6, "d":{"requestType": "SetProfileParameter", "requestId": "UUID", "requestData": {"parameterCategory": "Output", "parameterName": "FilenameFormatting", "parameterValue": "Test"}}}`

However, I haven't been able to figure out the parameter name and category for setting the recording location, and in general the SetProfileParameter doesn't seem to be particularly well documented.

**Comment by Qualzz** [comment]
For anyone looking for it:

```
cl.set_profile_parameter("SimpleOutput", "FilePath", recording_path)
value = cl.get_profile_parameter("SimpleOutput", "FilePath").parameter_value
print(value)
```
