### ISSUE TITLE
Bug: Crash

### ISSUE THREAD

**Issue by afriza** [obsproject/obs-websocket#1063]
### Operating System Info

macOS 10.15

### OBS Studio Version

28.1.x

### obs-websocket Version

5.0.1

### OBS Studio Log URL

https://obsproject.com/logs/p1bvdCaRm-6Kzjp2

### OBS Studio Crash Log URL

https://gist.github.com/afriza/e46cf0c24bb6fa4dfbba3a65c09384cf

### Expected Behavior

no crash

### Current Behavior

crash

### Steps to Reproduce

1. connect & subscribe to `General|Scenes`
2. send `GetCurrentProgramScene`
3. (maybe, I can't remember) Switch scene from OBS Studio app
...

### Anything else we should know?

It seems to crash in line 320 when calling `session->EventSubscriptions()`
https://github.com/obsproject/obs-websocket/blob/b07dce821af2942852d26cc092e29349433e4fd4/src/websocketserver/WebSocketServer.cpp#L313-L320

**Comment by tt2468** [comment]
By chance are you able to reproduce this with WebSocket debug logging enabled? Unfortunately it's hard to determine what exactly happened in the lead-up to this crash, so logging would help significantly.
