### ISSUE TITLE
OBS WebSocket 4.9 Bug: "The following OBS plugins faied to load: obs-websocket-compat"

### ISSUE THREAD

**Issue by krazerkap** [obsproject/obs-websocket#1070]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.x

### obs-websocket Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/biuEE6X5tYC-8o9D

### Expected Behavior

After installing WebSocket 4.9, I expected to be able to launch OBS and use it so that my Macro Deck could control my stream.  I downloaded and installed it and it worked once.  

### Current Behavior

Every time after the first install, OBS comes up and gives me the error: "The following OBS plugins faied to load: obs-websocket-compat"  It tells me to either update or uninstall.  Updating to version 5 does not help.  

### Steps to Reproduce

1. Install OBS WebSocket 4.9 and/or 5
2. Launch OBS
3. Error occurs on OBS startup.  
...

**Comment by tt2468** [comment]
OBS >= 28 includes obs-websocket 5.x by default, and does not need to be installed manually. The release description for 5.0.1 in the releases section states that it is for OBS 27 only.

The latest release on this repo is 4.9.1-compat for OBS 28: https://github.com/obsproject/obs-websocket/releases/tag/4.9.1-compat

**Comment by krazerkap** [comment]
If OBS 28 going forward includes it, how do I enable it?

**Comment by tt2468** [comment]
In the tools menu as it's always been.

You may need to use `Help -> Check for integrity` to repair your installation.

**Comment by krazerkap** [comment]
That fixed it.  Thanks.
