### ISSUE TITLE
Feature Request: Get Output Stats

### ISSUE THREAD

**Issue by TheLightningStrikes** [obsproject/obs-websocket#1075]
### Feature Request Type

RPC Request

### Requested Feature

Same as GetStats but for the output part so you can see bitrate, dropped frames (network) and total data output.

### Requested Feature Usage Scenario

Remote checking if your output bitrate is OK and if you are dropping network frames.

**Comment by tt2468** [comment]
https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getstreamstatus

**Comment by TheLightningStrikes** [comment]
Thanks for that :) sorry for not noticing it myself.
