### ISSUE TITLE
Feature Request: Add "On virtual Camera State"

### ISSUE THREAD

**Issue by Webmeesters1** [obsproject/obs-websocket#1076]
### Feature Request Type

RPC Event

### Requested Feature

In addition to "On Streaming State" and "On Recording State", add "On Virtual Camera State", so i know when virtual cam is active or not.

### Requested Feature Usage Scenario

I use OBS mainly for Online meetings, and control OBS with a tablet using Touch Panel. 
So i do not stream or Record, but use the VCam that i then use in Teams or Zoom.
Knowing the state of the VCam costs a lot of scripting in TP, and is not failsafe.

**Comment by tt2468** [comment]
We have the [`VirtualcamStateChanged`](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#virtualcamstatechanged) event which appears to be exactly what you're looking for.
