### ISSUE TITLE
Feature Request: Add "On Preview Scene Selected" event

### ISSUE THREAD

**Issue by Webmeesters1** [obsproject/obs-websocket#1077]
### Feature Request Type

RPC Event

### Requested Feature

Besides "On Scene Selected", please add "On Preview Scene Selected" to the interface

### Requested Feature Usage Scenario

I use OBS mainly for Online meetings, and control OBS with a tablet using Touch Panel. 
I have a row of buttons for the selected scene, and a row for the preview scene.
Based on the actual scene, i'd like to be able to show the active scene on both rows. 
I do that using variables now, but that isn't foolproof and tedious in maintenance.
Would be great just to have an event when the preview scene changes as well.
![afbeelding](https://user-images.githubusercontent.com/120177726/206687182-350c6a77-6623-4309-bc69-9a725e5d9674.png)
![afbeelding](https://user-images.githubusercontent.com/120177726/206687649-786d75ae-4cef-486c-9971-e1c7443b93bc.png)

**Comment by tt2468** [comment]
This should be usable in the form of the `PreviewSceneChanged` event.
