### ISSUE TITLE
Feature Request:  CreateSource and other Source Request for V5.0 +

### ISSUE THREAD

**Issue by sophy228** [obsproject/obs-websocket#1086]
### Feature Request Type

RPC Request

### Requested Feature

I found lots of Source releated request APIs are gone since V5.0 , compared with V4.9 
Any reason or do we have any planes to add them back ?

Thanks very much

### Requested Feature Usage Scenario

We want to use web-socket 5.0 souce APIs just like V4.9 to do  source releated remote controls.

**Comment by tt2468** [comment]
"Sources" were split into more descriptive requests for v5. 5.x is meant to have feature parity with 4.x, with some nuances.

The request you are looking for that roughly replaced `CreateSource` is `CreateInput`.
