### ISSUE TITLE
Bug: CMake Error at CMakeLists.txt:1 (project):   VERSION not allowed unless CMP0048 is set to NEW

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-websocket#1087]
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

28.1.x

### obs-websocket Version

5.1.0

### OBS Studio Log URL

n/a

### Expected Behavior

n/a

### Current Behavior

configure fails

### Steps to Reproduce

configure fails

### Anything else we should know?

cmake-3.24.3

**Comment by tt2468** [comment]
obs-websocket 5.x is not meant to be compiled out-of-tree.
