### ISSUE TITLE
Feature Request: Add "Set Scene Item Properties"

### ISSUE THREAD

**Issue by nknikolay** [obsproject/obs-websocket#1089]
### Feature Request Type

RPC Request

### Requested Feature

I would like to see the ability to change the **"local file"** in the **"media source"**.
Perhaps it makes sense to add the ability to change any parameters of the sources. 
I'm talking about the appearance of the `SetSceneItemProperties` request (and `GetSceneItemProperties` accordingly)

### Requested Feature Usage Scenario

I'm writing my own Twitch bot and I want to run different videos depending on the input of commands in the stream's chat.
I want to switch the scene to a specially prepared one, play a random video on it (out of 50 pre-arranged ones), and then switch the scene back.
I don't want to create a Browser Source for this, as it introduces additional delay.

**Comment by tt2468** [comment]
This already exists. See `SetInputSettings`.
