### ISSUE TITLE
Feature Request: Get Available Filter of Source and Set Filter Source

### ISSUE THREAD

**Issue by fedeocire** [obsproject/obs-websocket#1090]
### Feature Request Type

RPC Request

### Requested Feature

Get all Available Filter of Source and Set Source Filter

### Requested Feature Usage Scenario

Get all Available Filter of Source for select one and by Set Source Filter setting filter selected to Source

**Comment by tt2468** [comment]
Pretty sure this functionality is already implemented via `CreateSourceFilter` and `SetSourceFilterSettings`.
