### ISSUE TITLE
Feature Request: get an array of scenes from a given collection

### ISSUE THREAD

**Issue by fedeocire** [obsproject/obs-websocket#1092]
### Feature Request Type

RPC Request

### Requested Feature

get an array of scenes from a given collection

### Requested Feature Usage Scenario

obtain an array of scenes of a given collection as is done through the get_scene_item_list(SceneName) function to retrieve the sources of a scene. This is to allow an external application to preload all collections with their respective scenes and sources

**Comment by cezarsmpio** [comment]
👍

**Comment by tt2468** [comment]
This feature cannot be implemented, due to limitations of how OBS works. In order to get a list of scenes from a collection that is not the current one, you must switch to that collection first.

**Comment by cezarsmpio** [comment]
@tt2468 any idea how Elgato Stream Deck does that? When you select the switch obs scene button, it shows collections and scenes for the selected collection on the input. I'm wondering if they use this lib tho.

thanks @tt2468 for letting us know!

**Comment by tt2468** [comment]
It's probably relying on manually reading and parsing the scene collection .json files within the OBS config directory, something that I would consider out of scope of the objectives of obs-websocket.

**Comment by cezarsmpio** [comment]
I see, I will look into that. Thanks!
