### ISSUE TITLE
Feature Request:  How to check if statusbar is red - if stream is bad or has a bad connection

### ISSUE THREAD

**Issue by lassos** [obsproject/obs-websocket#1118]
### Feature Request Type

RPC Request

### Requested Feature

i have one question. is it also possible to check if the status bar is red ? sometimes we do not get a reconnect event but stream is going down from green to red for 10-20 seconds without disconnecting. is there a way to check this ? 

so we can check with

OBS_WEBSOCKET_OUTPUT_STARTING OBS_WEBSOCKET_OUTPUT_STARTED  
OBS_WEBSOCKET_OUTPUT_RECONNECTING OBS_WEBSOCKET_OUTPUT_RECONNECTED
OBS_WEBSOCKET_OUTPUT_STOPPING OBS_WEBSOCKET_OUTPUT_STOPPED

events. but how to get a possibility to trigger an event if the stream is going to red status. or is it possible to get or read the information about statusbar -> green/red

maybe anyonce has a hint for me .

### Requested Feature Usage Scenario

if stream is not disconnected but going slow  sometimes it is disconnected from website. so if there would be a notification  about red status i could trigger connection to a better server and if i even know status was red (that forced a desconnect from streaming websites) i could trigger a reconnect to this website

**Comment by bryce-seifert** [comment]
obs-websocket provides the outputCongestion via GetStreamStatus.

You can use this to determine the color, based on the formula used by the [OBS UI to generate the status bar](https://github.com/obsproject/obs-studio/blob/1be1f51635ac85b3ad768a88b3265b192bd0bf18/UI/window-basic-status-bar.cpp#L327)

**Comment by lassos** [comment]
woooooooooooooooooooow

i am waiting since week of this great answer. thaaaaaaaaaaaaaaaaaaaaaanks soooooo much

**Comment by lassos** [comment]
can someonce explain this line of code:

else if (fabsf(avgCongestion - 1.0f) < EPSILON) {

i think the is the red status but what means EPSILON ?

**Comment by bryce-seifert** [comment]
From a search, epsilon is:
>  the difference between 1.0 and the next value representable by the floating-point type T

In general, I'm not sure how close you want your implementation to be to the OBS UI, but values closer to 1.0 are going to be red, and 0.0 green. So you can simplify the function a bit if you don't need exact precision.

**Comment by lassos** [comment]
ok, it is working. i will check congestion every  60 seconds. but maybe it would be possible to add an eventy in future releases if status goes from to green to red like StreamStateChangedEvent

**Comment by tt2468** [comment]
Closing as it appears that this issue has been answered as best as possible.
