### ISSUE TITLE
Feature Request: get sourcename from sceneName and sceneItemId

### ISSUE THREAD

**Issue by awrebels** [obsproject/obs-websocket#1122]
### Feature Request Type

RPC Event

### Requested Feature

Currently using the SceneItemEnableStateChanged to trigger certain actions. However, it would be great to also have the sourceName for certain manipulation. 

Perhaps if it was included in the event as a datafield that would be great; rather than me calling a separate function to get the sourceName then the ID.

if anybody has another method or workaround lmk. thanks!

### Requested Feature Usage Scenario

In my case, I am essentially connecting two OBS instances with a similar scene collection structure. However, I want to confirm the scene item ID on the second system by sending the sourceName from system 1 and grabbing the correct sceneItemId from system 2.

**Comment by tt2468** [comment]
Hmm, that does seem like an oversight in the coverage of scene item/source associations. Will add it to my list to implement as `GetSceneItemSourceName`
