### ISSUE TITLE
Cannot configure WebSocket Plugin to bind to IPv4

### ISSUE THREAD

**Issue by houserockr** [obsproject/obs-websocket#1131]
### Operating System Info

Other

### Other OS

Alma Linux 9.1

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/mXBleDTVMQcit4B7

### Expected Behavior

The user should be able to configure the option `--websocket_ipv4_only` provided by obs-websocket in the WebSocket configuration dialog of OBS.

### Current Behavior

With ipv6 disabled on Alma Linux 9, the WebSocket plugin doesn't work, because it will bind to ipv6 by default, which will fail:

```
14:54:42.836: [obs-websocket] [WebSocketServer::onObsLoaded] WebSocket server is enabled, starting...
14:54:42.837: [obs-websocket] [WebSocketServer::Start] Not locked to IPv4 bindings
14:54:42.839: [obs-websocket] [WebSocketServer::Start] Listen failed: Address family not supported by protocol
```
However, I cannot find a way to configure the option `--websocket_ipv4_only` which obs-websocket provides. Me, personally, I wouldn't necessarily need an HMI option if there's another way to add that parameter to a script in the background.

The option has been added with:
https://github.com/obsproject/obs-websocket/pull/559
https://github.com/obsproject/obs-websocket/pull/928

### Steps to Reproduce

**Precondition**: Linux with ipv6 disabled by kernel option
1. Enable the WebSocket plugin in the configuration
2. Restart OBS
3. Check the log or
4. `$ sudo netstat -tapn | grep LISTEN`
...

**Comment by tt2468** [comment]
Do you have a use-case where you need to bind to IPv4 specifically? By default, obs-websocket binds to all interfaces on v6, which still allows v4 connections to be created. Someone previously had claimed that they could only connect if obs-websocket was locked to only IPv4, so I added the feature. I never added it to the UI because one user having an issue did not seem to warrant changing the UI.

**Comment by houserockr** [comment]
First of all, I can mitigate this observation to some extent, because it works now.

**Here's how the observation came about**:
- I started OBS with WebSocket enabled and I couldn't connect from the iOS OBS Controller app, even though both devices were logged into the same wifi network
- `$ netstat -tapn` revealed that OBS is *only* bound to ipv6
- I thought that must be the problem and disabled ipv6 via kernel option (`ipv6.disable=1`) to force WebSocket to bind to ipv4
- WebSocket failed to start, because I had no way to tell it to use `--websocket_ipv4_only`
- I created this issue *cough* 👼 
- I found an *additional* WebSocket extension called *WebSocket 4.x compat* on Alma Linux with `flatpak`
- Funnily enough said compat WebSocket extension integrates into the OBS ui and looks like this:
![Screenshot from 2023-04-30 11-26-32](https://user-images.githubusercontent.com/8655705/235346069-e0a5db98-6395-4af0-a498-974433a91162.png)
- See that it has a dedicated checkbox for the `--websocket_ipv4_only` option.
- However, it still didn't work, so I fired up wireshark to see what's happening
- No incoming connection **at all** - omg is the firewall active and blocking this port?
- `# iptables -L` showed no active chains and I deemed the firewall to be disabled
- But that wasn't the case, `iptables` is inconclusive, I had to `# systemctl stop firewalld` (and ultimately `# systemctl disable firewalld`)
- But it still didn't work with the compat extension
- I reverted everything with regard to OBS any my kernel back to ipv6 (i.e. "normal")
- It worked

**Here's how/why it still works**:
- Even though WebSocket is **only** bound to ipv6 in `netstat` (`tcp6 0 0 :::4455 :::* LISTEN`) it's accepting ipv4 connections, which I didn't know was possible 🙌 

**Here's the *use case* that still stands imho**:
It's more of a precondition than a use case. If OBS is running on a machine with ipv6 disabled, WebSocket won't run at all. I don't know if this only applies to Linux, but I assume it also applies to other OSs. Me personally, I've seen many machines with ipv6 still disabled by default, but I don't have any stats on that. I let you guys decide whether that's relevant or not.

**Comment by tt2468** [comment]
Fixed by creating a fallback to IPv6 if we get the address family not supported error: https://github.com/obsproject/obs-websocket/commit/6434c421556c25397d9af7b21365796cd6c7a715
