### ISSUE TITLE
Bug: Document description error

### ISSUE THREAD

**Issue by button-chen** [obsproject/obs-websocket#1137]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.x

### obs-websocket Version

5.1.0

### OBS Studio Log URL

https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md

### Expected Behavior

If a **text** frame is received when using the obswebsocket.json (default) subprotocol, or a **binary** frame is received while using the obswebsocket.msgpack subprotocol, the connection is closed with WebSocketCloseCode::MessageDecodeError.

### Current Behavior

If a **binary** frame is received when using the obswebsocket.json (default) subprotocol, or a **text** frame is received while using the obswebsocket.msgpack subprotocol, the connection is closed with WebSocketCloseCode::MessageDecodeError.

### Steps to Reproduce

1. Incorrect document description in bold font

**Comment by tt2468** [comment]
No such text exists in the current protocol documentation. The documentation does state this:

> If a binary frame is received when using the obswebsocket.json (default) subprotocol, or a text frame is received while using the obswebsocket.msgpack subprotocol, the connection is closed with WebSocketCloseCode::MessageDecodeError

This statement is correct. JSON is a text format, msgpack is a binary format.
