### ISSUE TITLE
Feature Request: Add some data about Lost frame

### ISSUE THREAD

**Issue by LeProgGamer** [obsproject/obs-websocket#1139]
### Feature Request Type

Other

### Feature Request Type (Other)

Recuperation of data

### Requested Feature

Have a way to recover this data ?

- Missed images due to a delay in rendering
- Skipped frames due to encoding delay

Could be useful for a "report" page for OBS
![image-1-1](https://github.com/obsproject/obs-websocket/assets/22852247/17aa0c28-a9fc-4b62-b9f7-7827bba8af92)

### Requested Feature Usage Scenario

I have actually one screen tonstream and use Touche Portal with Web Socket to have some "report" page and control lot of thing with OBS 

Sometimes my stream Lost some Key, I want to know when it happened and I cannot sée it because these data are not implemented inside Web Socket

**Comment by tt2468** [comment]
This data is available via `GetStats`: https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getstats
