### ISSUE TITLE
Bug:  GetInputPropertiesListPropertyItems

### ISSUE THREAD

**Issue by hanxiang-li** [obsproject/obs-websocket#1164]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.x

### OBS Studio Version (Other)

29.1.3

### obs-websocket Version

5.1.0

### OBS Studio Log URL

https://obsproject.com/logs/OvFV6qOGQflsrjkW

### Expected Behavior

    obs.call('GetInputPropertiesListPropertyItems', {
        inputName: 'test',
        propertyName: 'display'
    }).then(res => {
        console.log(res)
    })

Display a list of displays

### Current Behavior

   Error: Unable to find a property by that name.

### Steps to Reproduce

    obs.call('GetInputPropertiesListPropertyItems', {
        inputName: 'test',
        propertyName: 'display'
    }).then(res => {
        console.log(res)
    })

### Anything else we should know?

I cannot obtain it on Windows for testing, Mac can

**Comment by hanxiang-li** [comment]
The document did not indicate that the following code is correct    

obs.call('GetInputPropertiesListPropertyItems', {
        inputName: 'Monitor' + timer,
        propertyName: 'monitor_id'
})

**Comment by AirplanegoBrr** [comment]
> The document did not indicate that the following code is correct
> 
> obs.call('GetInputPropertiesListPropertyItems', { inputName: 'Monitor' + timer, propertyName: 'monitor_id' })

what is `timer`, where do you find it?? What is `monitor_id` where do you find that as well??

**Comment by hanxiang-li** [comment]
The timer is customized by me, so I don't need to pay attention. In the Windows environment, the parameter passed to obtain the screen ID is monitor_ The ID and MAC environment are display, which is what I obtained from browsing the OSS source code

**Comment by hanxiang-li** [comment]
The timer is customized by me, so I don't need to pay attention. In the Windows environment, the parameter passed to obtain the screen ID is monitor_ The ID and MAC environment are display, which is what I obtained from browsing the OSS source code

--------------原始邮件--------------
发件人："AirplaneGoBrr ***@***.***&gt;;
发送时间：2023年9月9日(星期六) 凌晨1:23
收件人："obsproject/obs-websocket" ***@***.***&gt;;
抄送："hanxiang ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [obsproject/obs-websocket] Bug:  GetInputPropertiesListPropertyItems (Issue #1164)
-----------------------------------

 


The document did not indicate that the following code is correct文档并没有表明下面的代码是正确的：

obs.call('GetInputPropertiesListPropertyItems', { inputName: 'Monitor' + timer, propertyName: 'monitor_id' })

what is 什么是timer, where do you find it?? What is ，你在哪里找到它？？什么是monitor_id where do you find that as well??你在哪里找到的？

—和mdash
