### ISSUE TITLE
Bug: obs-websocket-compat 4.9.1-compat-1 not loading on Ubuntu 22.04 with OBS 29.1.3

### ISSUE THREAD

**Issue by Corben78** [obsproject/obs-websocket#1166]
### Operating System Info

Ubuntu 22.04 LTS

### OBS Studio Version

29.0.x

### obs-websocket Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/xOzzTxFz9vIBvKCk

### Expected Behavior

obs-websocket-compat being loaded in OBS 29.1.3 and not giving an error.

### Current Behavior

![grafik](https://github.com/obsproject/obs-websocket/assets/8013933/b4f41de5-cc98-42c2-a5da-edec300590bd)

### Steps to Reproduce

1. Download  obs-websocket-4.9.1-compat-Ubuntu64.deb from https://github.com/obsproject/obs-websocket/releases
2. Install on Ubuntu 22.04 with gdebi obs-websocket-4.9.1-compat-Ubuntu64.deb
3. Start OBS

### Anything else we should know?

`ldd /usr/lib/x86_64-linux-gnu/obs-plugins/obs-websocket-compat.so` shows it's linked to Qt5, shouldn't it be linked to Qt6?
```
libQt5Widgets.so.5 => /lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f679f800000)
libQt5Gui.so.5 => /lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f679f000000)
libQt5Core.so.5 => /lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f679ea00000)
```

**Comment by Corben78** [comment]
Oh, looks like this got already reported in #997

**Comment by lancer1977** [comment]
fyi, I had to install version 27 for the plugin to work.

**Comment by tt2468** [comment]
Sorry, but at this point we have no intention of touching any of the old 4.x-compat stuff.
