### ISSUE TITLE
Feature Request: Show or hide a source

### ISSUE THREAD

**Issue by TheBartoMan** [obsproject/obs-websocket#1174]
### Feature Request Type

RPC Request

### Requested Feature

I would like to be able to show or hide a source?

Is this possible?

All i can find is trying to do it via TriggerHotkeyByName. (however Show works, but hide doesnt as people have reported)
I would try TriggerHotkeyByKeySequence, but there are no working examples of how to do this. Tried countless ways!

### Requested Feature Usage Scenario

The ability to show or a hide a source easily

**Comment by tt2468** [comment]
This is not the place to ask for support for obs-websocket. Only submit feature requests if you know for a fact that the feature does not exist.

You are looking for `SetSceneItemEnabled`
