### ISSUE TITLE
Feature Request: Add GetSourceFilterKindList and GetFilterKindList requests

### ISSUE THREAD

**Issue by jdudetv** [obsproject/obs-websocket#1198]
### Feature Request Type

RPC Request

### Requested Feature

Add a request that takes in Source / Input name and gives all the filter kinds that can be applied to that input kind / source and a request that just gives a list of all FilterKinds currently available in OBS.

### Requested Feature Usage Scenario

When applying a filter to a source having a list of all compatible filter kinds before applying the filter. Having the full FilterKindsList would help in just having a way to get all filter kinds that are available for the entire app if stuff isn't documented by plugins etc.

**Comment by Brendonovich** [comment]
`GetSourceFilterKindList` will probably need to use a copy of [`filter_compatible`](https://github.com/obsproject/obs-studio/blob/1e09f5a543b107fb092a50175530a667e5a33fa4/UI/window-basic-filters.cpp#L476), and it might be a good idea to use the same logic inside `CreateSourceFilter` to ensure the provided filter kind is compatible with the provided source.

**Comment by tt2468** [comment]
Added a note to implement compatibility checks for filters. Not in scope for this feature request though
