### ISSUE TITLE
Feature Request: allow un/subscribing to events post-connection

### ISSUE THREAD

**Issue by Yagich** [obsproject/obs-websocket#1204]
### Feature Request Type

RPC Request

### Requested Feature

Currently, the only way to subscribe/unsubscribe to events is possible at initialization. It would be nice to have a way to un/subscribe to events at any point during a connection.

### Requested Feature Usage Scenario

I'm working on an app that allows users to interface with OBS via obs-websocket with a node graph interface. I want to provide the full feature set of obs-websocket through nodes, while also starting off with "sane" defaults so that the the high-volume events are still available, but after some configuration.

**Comment by david672orford** [comment]
I haven't tried it, but according to the documentation there is a Reidentify message (opcode 3) your client can send to change its event subscriptions.

**Comment by tt2468** [comment]
@david672orford is correct, you can already achieve this event subscription modification behavior via Reidentify.
