### ISSUE TITLE
Bug: [WebSocket] SetSceneItemTransform sends "Failed" response, but succeds

### ISSUE THREAD

**Issue by hgdagon** [obsproject/obs-websocket#1233]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.2

### obs-websocket Version

5.1.0

### OBS Studio Log URL

https://obsproject.com/logs/CPH5DCmtBSJCbrfq

### Expected Behavior

Correct Response

### Current Behavior

I'm using simpleobsws to change the transform of a GDI text source.

```Python
request = simpleobsws.Request('SetSceneItemTransform', {'sceneName': 'My_Scene', 'sceneItemId': 7, 'sceneItemTransform': {'width': 100'}})
response = await self.bot.ws.call(request)
print(response.requestStatus)
```
The status prints out as:
```Python
RequestStatus(result=False, code=703, comment='You have not provided any valid transform changes.')
```

The problem, however, is that the request actually succeeds, as in the width of the item does change.

### Steps to Reproduce

1. Send a SetSceneItemTransform WebSocket request providing only the width in sceneItemTransform
2.
3.
...

### Anything else we should know?

WebSocket version is 5.4.2.

**Comment by tt2468** [comment]
This fails because `width` is not a valid request parameter. Please consult the documentation before opening Github issues.

**Comment by hgdagon** [comment]
I don't get it. GetSceneItemTransform returns this:
```Python
{
  "sceneItemTransform": {
    "alignment": 8,
    "boundsAlignment": 0,
    "boundsHeight": 1.0,
    "boundsType": "OBS_BOUNDS_NONE",
    "boundsWidth": 1.0,
    "cropBottom": 0,
    "cropLeft": 0,
    "cropRight": 0,
    "cropTop": 0,
    "height": 61.90977478027344,
    "positionX": 960.0,
    "positionY": 630.0,
    "rotation": 0.0,
    "scaleX": 0.17290551960468292,
    "scaleY": 0.17293232679367065,
    "sourceHeight": 358.0,
    "sourceWidth": 2688.0,
    "width": 464.7700500488281
  }
}
```
So, how is `width` not valid?

**Comment by tt2468** [comment]
`width`, `height`, `sourceWidth`, `sourceHeight` are all read-only values that only exist in `GetSceneItemTransform`. Use `scaleX` and `scaleY` to scale a scene item.
