### ISSUE TITLE
Bug: Devs Aren't making any progress on default features.

### ISSUE THREAD

**Issue by zachtie** [obsproject/obs-websocket#1276]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.x

### obs-websocket Version

5.1.0

### OBS Studio Log URL

No

### Expected Behavior

I expect a feture thats in OBS natively to get updates for functionality thats been asked for for 2 years and is a medium priority.

### Current Behavior

Devs Have not added the ability to set scene show and hide transitions. Its been 2 years.

### Steps to Reproduce

1. Search your issue
2. Find that its already been an issue for 1 year
3. Make a post.
4. Post gets ignored despite the feature being a native function thats not implimented, becaus ethe devs are doing who knows what.
...

### Anything else we should know?

WHEN WILL YOU ADD IN THE FUNCTIONALITY TO SET THE SHOW/HIDE TRANSITION ON A SOURCE ADDED VIA THE WEBSOCKET? FK.

**Comment by tt2468** [comment]
Yelling at the maintainers of free, zero-warranty, open source software is not a very reliable method of getting the features that you want implemented. We are volunteers, and quite frankly, I have no obligation to serve you in the first place.
