### ISSUE TITLE
Feature Request: Swap Preview Output after Transitioning Command

### ISSUE THREAD

**Issue by DeeJayMX** [obsproject/obs-websocket#187]
Please add this command in the protocol,

To get the switching when triggering the Cut and or the Auto Trans.

![image](https://user-images.githubusercontent.com/36418772/36111832-c0ac6232-1027-11e8-9840-2fe150329eb1.png)

**Comment by DeeJayMX** [comment]
Do you have some news ?

**Comment by tt2468** [comment]
Implemented as `TriggerStudioModeTransition` in upcoming 5.0.0
