### ISSUE TITLE
Feature Request/Todo: Callback & Signals API

### ISSUE THREAD

**Issue by Palakis** [obsproject/obs-websocket#288]
##### Issue type
Feature request

##### Description
Sources expose callbacks (that can be called) and signals (that can be emitted). These sources can expose additional functionality through these, so it could be useful to expose it to users (for example: restart a media source).

##### Tasks
- [ ] Part 1: Callback API
- [ ] Part 2: Listen for signals (depends on #275)

**Comment by tt2468** [comment]
Closing as basically done
