### ISSUE TITLE
Feature Request: Release distro-agnostic Linux tarballs to extract into $XDG_CONFIG_HOME/obs-studio/plugins

### ISSUE THREAD

**Issue by HugLifeTiZ** [obsproject/obs-websocket#442]
##### Issue type
Feature Request

##### Description
Request for a Linux distribution-agnostic method to install the websockets plugin for a regular user without using a package manager.

##### Steps to reproduce and other useful info
This request is useful for anyone running the Flatpak version of OBS Studio on Linux, and especially useful for those on non-Debian distros. I was curious to see if the library in the Debian package would work as is, so using the release tarball from [Linux Browser Plugin](https://github.com/bazukas/obs-linuxbrowser/releases) as a guide, I changed the directory structure like so and placed it in `$XDG_CONFIG_HOME/obs-studio/plugins`:

```
obs-websocket/bin/64bit/obs-websocket.so
obs-websocket/data/locale/*.ini
```

When I started up my Flatpak OBS Studio, it worked just fine. It's likely you can just distribute it this way as-is.

##### Technical information
- **Operating System** : Xubuntu 18.04
- **OBS Studio version** : 25.0.1, through Flatpak

**Comment by HugLifeTiZ** [comment]
Hey there. I just got a pull request merged for OBS Studio on flathub that creates an extension point for plugins, and I've been using this plugin to test it. I'll be making an app submission request for the flatpak version of this plugin; do you guys want to be involved in that in any way? Like, to have ownership of the resulting repo or anything like that?

**Comment by tt2468** [comment]
Closing as this is no longer relevant to obs-websocket (due to upcoming bundling with obs-studio)
