### ISSUE TITLE
Feature Request: motion-effects integration

### ISSUE THREAD

**Issue by B00TK1D** [obsproject/obs-websocket#525]
##### Description
It would be super helpful if obs-websockets could control control the motion-effects plugin.  It just needs two triggers per motion-effect filter: trigger motion forward and trigger motion backwards.  I'm not sure if this could be done just in obs-websockets, or if it would take work in motion-effects too.  However, this would allow things like a streamdeck to control motion-effects.

**Comment by tt2468** [comment]
This would require #288

**Comment by riegel** [comment]
Wow, this is an awesome plugin. I am currently using it to build a joystick controller for positioning a scene, I am not sure if #288 applies to my particular situation but...

I am looking for a way to "Stop" any currently running transition.

I want to be able to start a motion effect in a particular direction and trigger a stop.

Is this possible?

Thanks again for a nice tool.

**Comment by tt2468** [comment]
@riegel You can try to perform the motion by using `SetTbarPosition`. Otherwise, no way to stop a transition mid-cycle.

**Comment by DachsbauTV** [comment]
I've used to use motion-effect but recently stumbled upon this https://obsproject.com/forum/resources/move-transition.913/ and switched, because move-transition has a more active community around it (motion effect hasn't been updated for 3 years). Also it just has more features and works easier.

**Comment by tt2468** [comment]
Will be possible in 5.0.0, so long as the motion-effects plugin developers use our `obs-websocket-api.h` (not yet finished)
