### ISSUE TITLE
Feature Request: Machine Readable Protocol Description

### ISSUE THREAD

**Issue by harm27** [obsproject/obs-websocket#602]
##### Issue type
 - Feature request 

##### Description
While developing my [Java Client Library](https://github.com/harm27/obs-java-client) for OBS Websocket, quickly noticed a lot of overhead in coding every event and request manualy, what would increase the time in getting changes in existing or new Events or Requests added to my Client Library.

To solve that, i wrote a Maven plugin for my Library that uses the [comments.json](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/comments.json) file of the current main branch to generate a lot of the classes so that when a new OBS Websocket version would be released, it would require less work to get a new client library version released, so that a user of my library would have a new version available quickly. 

But the current solution has some flaws, since the comments.json file isn't designed for this use case, but also some other problems:

- Mix of naming styles (Already on the list for 5.0 i saw).
- Categories like Recording, Streaming, etc. are not in one array in that file so that i need to add them one by one. 
- Multi-layered objects sometimes are mentioned on there own and as part of there sub properties and sometimes only as part of there sub properties. (Mightly some what solved by transforming multi-level JSON into single-level, that is on the list for 5.0)
- Missing info about Base-Event, -Request and -Response

And when the HTTP Endpoint becomes available, it would be nice if that would also have a Machine Readable Protocol Description.

Or when other message solutions then JSON would become available like MessagePack i saw being mentioned, that there would be a Machine Readable Protocol Description.

**Comment by harm27** [comment]
Another item that would be the new error codes, that next to that they are descripted in the description, that they are also added to the protocol description file, so that could also be generated.

**Comment by tt2468** [comment]
Would you be able to check out the current `protocol.json` and let me know what you think?

**Comment by harm27** [comment]
Hi,

It looks really nice. 

I stopped developing my client because of time constraints and my use case dissapearing, but probably it will be usefull to someone else.

**Comment by tt2468** [comment]
Good to hear that it has improved.
