### ISSUE TITLE
Feature Request: Get last created replay buffer file

### ISSUE THREAD

**Issue by eddedre** [obsproject/obs-websocket#640]
##### Issue type
Feature request

##### Description
We have a need to be able to able to get the last created replay buffer file name so we can use it for clip tracking / database usage.

There is a lua script that does this currently
`local replay_buffer = obs.obs_frontend_get_replay_buffer_output()`
`-- Call the procedure of the replay buffer named "get_last_replay" to`
`-- get the last replay created by the replay buffer`
`local cd = obs.calldata_create()`
`local ph = obs.obs_output_get_proc_handler(replay_buffer)`
`obs.proc_handler_call(ph, "get_last_replay", cd)`
`local path = obs.calldata_string(cd, "path")`

**Comment by tt2468** [comment]
Planned for 5.0.0
