### ISSUE TITLE
Feature Request: Streaming Network Status

### ISSUE THREAD

**Issue by Thelvaen** [obsproject/obs-websocket#675]
##### Issue type
- Feature request

##### Description
It would be interesting to get network status (actual bitrate, configured bitrate, image loss %) available somewhere, so it can be displayed on a deckboard or something.

My ISP seems to have some Peering issue with Twitch (or with the intermediary operator, I'm not sure about that part), hence I'd like to detect when my upload bitrate goes really under the 6000kb/s configured so I can either stop streaming or try to change the ingest server I'm connected to.

The idea is to provide the Streaming part of the Stats window. At the moment the GetStats endpoint only provide the top part of the window, I'd like to have the bottom part (to try to work around my ISP issue).

![obs_stats](https://user-images.githubusercontent.com/19350574/107714545-c8ecf500-6ccd-11eb-8046-e4eed062e0b3.png)

**Comment by tt2468** [comment]
To be available in 5.0.0 via `GetStats`
