### ISSUE TITLE
Feature Request: More Variables

### ISSUE THREAD

**Issue by DachsbauTV** [obsproject/obs-websocket#716]
Hi amazing people,

I think a couple more variables could go a long way for this module. The most exciting ones I've found are these:

- remaining time and/or state of a playing media source 
- current playing media file name and/or in vlc playlists: next media file name
- Text(GDI+) variable (see the content of a dynamic lower third on a streamdeck button before putting it on program)

P.S.: I've just understood the structure behind this and the companion obs module, that's why I've opened this issue here now as well https://github.com/bitfocus/companion-module-obs-studio/issues/72

**Comment by Marcuzzz** [comment]
Not sure if this is related but I would like to send and receive some custom variables to the OBS Websocket.
I've created a "frontend" function; random scene switch, but I would like to let other "users" know about the fact the random switch is on and I would like another user to be able to switch it off...

**Comment by tt2468** [comment]
This is unrelated to obs-websocket's repo here, so I'll be closing this.
