### ISSUE TITLE
Feature Request: Show sources names in groupChildren from GetSceneItemProperties 

### ISSUE THREAD

**Issue by DhSufi** [obsproject/obs-websocket#721]
Issue type

    Feature request

Description

When **_GetSceneItemProperties_** is called in reference a group, it returns, amog others, the response item _**groupChildren**_

The **_groupChildren_** shows a list with a lot of information about each source inside the group but it does not return the name of the source. (See example)

I propose if possible to add the **_name_** of the source in the list of the parameters returned by **_groupChildren_**

As always, thanks a lot for your time and consideration. Best regards.

Example:

    {'bounds': {'alignment': 0, 'type': 'OBS_BOUNDS_NONE', 'x': 0.0, 'y': 0.0}, 'crop': {'bottom': 0, 'left': 0, 'right': 0, 'top': 0}, 'groupChildren': [{'bounds': {'alignment': 0, 'type': 'OBS_BOUNDS_NONE', 'x': 0.0, 'y': 0.0}, 'crop': {'bottom': 0, 'left': 0, 'right': 0, 'top': 0}, 'height': 0.0, 'locked': False, 'parentGroupName': 'Grupo', 'position': {'alignment': 5, 'x': 0.0, 'y': 0.0}, 'rotation': 0.0, 'scale': {'filter': 'OBS_SCALE_DISABLE', 'x': 1.0, 'y': 1.0}, 'sourceHeight': 0, 'sourceWidth': 0, 'visible': True, 'width': 0.0}, {'bounds': {'alignment': 0, 'type': 'OBS_BOUNDS_NONE', 'x': 0.0, 'y': 0.0}, 'crop': {'bottom': 0, 'left': 0, 'right': 0, 'top': 0}, 'height': 0.0, 'locked': False, 'parentGroupName': 'Grupo', 'position': {'alignment': 5, 'x': 0.0, 'y': 0.0}, 'rotation': 0.0, 'scale': {'filter': 'OBS_SCALE_DISABLE', 'x': 1.0, 'y': 1.0}, 'sourceHeight': 0, 'sourceWidth': 0, 'visible': True, 'width': 0.0}], 'height': 0.0, 'itemId': 3, 'locked': False, 'name': 'Grupo', 'position': {'alignment': 5, 'x': 0.0, 'y': 0.0}, 'rotation': 0.0, 'scale': {'filter': 'OBS_SCALE_DISABLE', 'x': 1.0, 'y': 1.0}, 'sourceHeight': 0, 'sourceWidth': 0, 'status': 'ok', 'visible': True, 'width': 0.0}

Technical information

    Operating System : Windows 10
    OBS Studio version : 26.1.1
    obs-websocket version : 4.9.0

**Comment by tt2468** [comment]
Closing as unrelated to 5.0.0
