### ISSUE TITLE
Feature Request: Toggle individual sources in Groups when the sources have the same name (nested scenes)

### ISSUE THREAD

**Issue by Majow** [obsproject/obs-websocket#734]
##### Issue type

- Feature request

##### Description
When you have 2 sources with the same name in a group (generally 2 or more nested scenes will have this behavior) or in different groups you can't show/hide/toggle the source because it's name is shared. This behavior appears when you add the same scene several times but you want to toggle just one specific. It doesn't matter where if one or more groups are used. The commands to show/hide will usually 'bind' to the first from the bottom-up. Toggling the group itself works fine.

##### Steps to reproduce and other useful info
Create something like that:

> TESTSCENE
>    - GROUP_A
>     - NESTED_SCENE_A
>     - NESTED_SCENE_A
>     - NESTED_SCENE_B
>     - OTHER_SOURCES
>    - GROUP_B
>     - NESTED_SCENE B 
> SCENE_A
> SCENE_B

Try to toggle individually nested_scenes in group A or B. Usually the commands will be stuck to just one and the other one will be unreacheable.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : OBS 26.1.1 and 27.0.0-rc2
- **obs-websocket version** : 4.9

**Comment by tt2468** [comment]
Can be worked around in 5.0.0. 5.x no longer recurses groups, preventing unintentional scene item selection.
