### ISSUE TITLE
Bug: SetSyncOffset changes the value shown on the OBS GUI but not the effective setting

### ISSUE THREAD

**Issue by YorVeX** [obsproject/obs-websocket#799]
##### Issue type

- Bug report

##### Description
When I am changing the sync offset for "Mic/Aux" using the SetSyncOffset call from obs-websocket the change
1. is reflected in the GUI when I check it in OBS
2. is sent to me from obs-websocket via SourceAudioSyncOffsetChanged update
3. is not applied to any recordings I start, e.g. after I changed the offset from 0 ms to 500 ms everything is still in sync

##### Steps to reproduce and other useful info
- Leave the Sync Offset setting for Mic/Aux set to 0, start a test recording and verify that audio is in sync (assuming that with the test setup everything is in sync when the offset is set to 0 ms).
- Call SetSyncOffset via obs-websocket and set it to 500 ms (value 500000000 for the offset JSON field).
- In OBS open the Advanced Audio Properties -> the value is changed to 500 ms for Mic/Aux
- Close the Advanced Audio Properties dialog without changing anything and start another test recording. The expected behavior would be that audio and video is now out of sync, but it isn't.
- In OBS once again open the Advanced Audio Properties -> change the value for Mic/Aux to 501 ms, then back to 500 ms.
- Start another test recording, now the audio is out of sync, the change was finally applied.

The same applies to changes in all directions. If the 500 ms setting has been done through the GUI and is effective changing the setting back to 0 using SetSyncOffset only changes it in the GUI but it's not effective in the recording, same goes for -500 ms.

Maybe OBS is saving the audio sync setting in two places, one that's shown in the GUI and another one that is actually applied, and SetSyncOffset only changes the GUI setting but not the effective one?

##### Technical information
- **Operating System** : Windows 10 Pro 64 Bit
- **OBS Studio version** : 27.0.1
- **obs-websocket version** : 4.9.1

**Comment by tt2468** [comment]
Seems identical with setting the enabled tracks. Requires fixes on the OBS side. Will PR them sometime after 27.1

**Comment by tt2468** [comment]
Looked into this deeper. I'm not seeing anything that could cause the sync offset to not be changed. We change the sync offset the same exact way as the UI does, and the UI updating means that the value is truly changed. Would you be willing to try again to make sure that it isn't a fluke?

**Comment by P5-2p** [comment]
- @YorVeX

**Comment by YorVeX** [comment]
> Looked into this deeper. I'm not seeing anything that could cause the sync offset to not be changed. We change the sync offset the same exact way as the UI does, and the UI updating means that the value is truly changed. Would you be willing to try again to make sure that it isn't a fluke?

Thanks for looking into this.
I did quite a lot of testing back and forth, also with several OBS restarts between tests, so I am pretty sure. But yeah, no problem, when I got OBS fired up anyway I will run another test to eliminate the last bit of doubt. Will then report here again.

**Comment by tt2468** [comment]
Anything on this?

**Comment by YorVeX** [comment]
I tried again now (still on 27.0.1, I'm afraid to update because of the NDI A/V desync issues people are currently reporting) and indeed can no longer reproduce it. Maybe there is an extra condition that needs to be met for this problem to be triggered or I am just starting to go crazy. Either way, closing this for now and if it should come back I would reopen it only if I can find out what that extra condition is and add that to the scenario.

**Comment by YorVeX** [comment]
For others who find this issue at some later point: apparently there seems to be a bug with when changing the sync offset is becoming effective in OBS itself: https://github.com/obsproject/obs-studio/issues/5356

Maybe this was what I actually had problems with and SetSyncOffset via OBS websocket simply is affected by this bug rather than this being a bug in OBS websocket.
