### ISSUE TITLE
Bug: Events don't fire reliably

### ISSUE THREAD

**Issue by CShark** [obsproject/obs-websocket#804]
##### Issue type
- Bug report

##### Description
Some of the events don't fire reliably.
- PreviewSceneChanged sometimes only fires the first time it is triggered. Every subsequent selection does not fire the event. Or it doesn't fire at all.
- SceneCollectionChanged doesn't fire at all when changing the scene collection

##### Steps to reproduce and other useful info
For me, this reliably happens as soon as I call GetSceneList. After this I don't get any events on the connection until I reestablish a new WebSocket connection.

##### Technical information
- **Operating System** :
Win 10 Build 19042
- **OBS Studio version**:
27.0.1
- **obs-websocket version**
4.91.

##### Development Environment
Not sure if the error is because of the API I use or in the plugin itself. All events are consumed using the .NET implementation [obs-websocket-dotnet](https://github.com/BarRaider/obs-websocket-dotnet)

**Comment by CShark** [comment]
Found the bug. The WebSocket implementation does not allow multiple concurrent calls over the same connection. I.e. if I handle the PreviewSceneEvent, I have to return the handler, *before* I go on to trigger more requests. Otherwise the websocket connection will deadlock. If this is by design, I'll raise an issue with the .net implementation to make it run event handlers async.

**Comment by tt2468** [comment]
Requests are designed to be asynchronous in obs-websocket. This should not be an issue with the server. I suggest contacting the maintainers of the client library.
