### ISSUE TITLE
Ubuntu installation problem

### ISSUE THREAD

**Issue by HOLOBUR** [obsproject/obs-websocket#811]
When try to install "obs-websocket-5.0.0-alpha1-Ubuntu64.deb" or lower versions in a Ubuntu Server these message appear "Setting up obs-websocket (5.0.0-alpha1-1) ..." and nothing more happend
The installation is not completed (In OBS Studio doesn`t appear the websocket configuration in Tools menu

**Comment by tt2468** [comment]
Please provide a full dpkg log.

**Comment by HOLOBUR** [comment]
##### Issue type


Bug report


##### Description
When try to install "obs-websocket_4.9.1-1_amd64.deb" or lower versions in a Ubuntu Server these message appear "Setting up obs-websocket (5.0.0-alpha1-1) ..." and nothing more happen

##### Steps to reproduce and other useful info
sudo dpkg -i obs-websocket_4.9.1-1_amd64.deb

The log shows:
      2021-08-31 09:13:45 upgrade obs-websocket:amd64 4.9.1-1 4.9.1-1
      2021-08-31 09:13:45 status half-configured obs-websocket:amd64 4.9.1-1
      2021-08-31 09:13:45 status unpacked obs-websocket:amd64 4.9.1-1
      2021-08-31 09:13:45 status half-installed obs-websocket:amd64 4.9.1-1
      2021-08-31 09:13:46 status half-installed obs-websocket:amd64 4.9.1-1
      2021-08-31 09:13:46 status unpacked obs-websocket:amd64 4.9.1-1
      2021-08-31 09:13:46 status unpacked obs-websocket:amd64 4.9.1-1
      2021-08-31 09:13:46 configure obs-websocket:amd64 4.9.1-1 4.9.1-1
      2021-08-31 09:13:46 status unpacked obs-websocket:amd64 4.9.1-1
      2021-08-31 09:13:46 status half-configured obs-websocket:amd64 4.9.1-1
      2021-08-31 09:13:46 status installed obs-websocket:amd64 4.9.1-1
##### Technical information
- **Operating System** :    Ubuntu 18.04.5 LTS 
- **OBS Studio version** :   OBS 27.0.1
- **obs-websocket version** :   obs-websocket_4.9.1-1_amd64.deb

**Comment by tt2468** [comment]
Installing the deb package on Ubuntu 20.04 seems to work fine for both the debug version and the non-debug version:

```
tt2468@tt2468-Z440-Ubuntu:~$ sudo dpkg -i obs-websocket-0ccc344-git-debug-Ubuntu64.deb
Selecting previously unselected package obs-websocket.
(Reading database ... 338065 files and directories currently installed.)
Preparing to unpack obs-websocket-0ccc344-git-debug-Ubuntu64.deb ...
Unpacking obs-websocket (0ccc344-git-1) ...
Setting up obs-websocket (0ccc344-git-1) ...
tt2468@tt2468-Z440-Ubuntu:~$
```

```
tt2468@tt2468-Z440-Ubuntu:~$ sudo dpkg -i obs-websocket-5.0.0-alpha1-Ubuntu64.deb
Selecting previously unselected package obs-websocket.
(Reading database ... 338065 files and directories currently installed.)
Preparing to unpack obs-websocket-5.0.0-alpha1-Ubuntu64.deb ...
Unpacking obs-websocket (5.0.0-alpha1-1) ...
Setting up obs-websocket (5.0.0-alpha1-1) ...
tt2468@tt2468-Z440-Ubuntu:~$
```

**Comment by tt2468** [comment]
Please note that 5.0.0 is for developers only. It uses a new protocol which no applications currently support.

**Comment by HOLOBUR** [comment]
In Ubuntu 20.04.5 the problem persists and the dpkg log are the same

**Comment by HOLOBUR** [comment]
It works if use obs-websocket_4.5.1-1_amd64.deb

**Comment by tt2468** [comment]
I'm unable to replicate the issue.

**Comment by tt2468** [comment]
Closing as I am still unable to reproduce this issue.
