### ISSUE TITLE
Plugin doesn't appear in Tools menu (Pop OS 21.04)

### ISSUE THREAD

**Issue by n-sweep** [obsproject/obs-websocket#834]
##### Issue type

- Bug report

##### Description

obs-websocket installs but does not show up in OBS

logfile: https://gist.github.com/n-sweep/078b0aac810f478d798382e0941799bf

##### Steps to reproduce and other useful info

1. Install obs-websocket per the installation instructions
2.  Open OBS, there is no Websockets Server selection under the Tools menu

##### Technical information
- **Operating System** : Pop OS 21.04
- **OBS Studio version** : 27.1.3
- **obs-websocket version** : 4.9.1

**Comment by tt2468** [comment]
Popos always installs to the wrong directory. Try

```bash
sudo mv /usr/lib/obs-plugins/obs-websocket.so /app//lib/obs-plugins/
sudo mv /usr/share/obs/obs-plugins/obs-websocket /app//share/obs/obs-plugins/
```
