### ISSUE TITLE
Bug: 4.9.1 version prevents OBS studio from starting on Mac OS 10.13.6

### ISSUE THREAD

**Issue by chrislowth** [obsproject/obs-websocket#849]
##### Issue type

Bug report

##### Description

Version 4.9.1 of obs-websocket causes obs-studio to crash (fail to start) when run on MacOS 10.13.6.

Version 4.9.0 of obs-websocket works fine (but lacks a few nice new exposed commands).

It looks to me as if the 4.9.1 has been built on MacOS 11 without specifying the backwards compatibility flags that would allow it to run on MacOS 10 as well., where as 4.9.0 was built on MacOS 10 meaning it works on both v11 and v10 systems.

##### Steps to reproduce and other useful info

1. Install OBS studio 27.1.3 on MacOS 10.13.6 and run it - it runs fine.

2. Close it down

3. Install obs-websocket 4.9.1

4. Try to start OBS studio - it wont start.

5. Delete the obs-websocket.so file and retry  - OBS studio now starts. So close it down again.

6. Install obs-websocket 4.9.0 and retry - this time OBS studio starts and the plugin is enabled.

##### Technical information

- **Operating System** : Mac OS 10.13.6
- **OBS Studio version** : 27.1.3
- **obs-websocket version** : 4.9.1

**Comment by tt2468** [comment]
Can you provide an OBS log of a time that it failed to start OBS? You can go to `Help -> Log Files -> Upload Last Log`

**Comment by chrislowth** [comment]
I'm really sorry, but I can't - I've handed the laptop back with the 4.9.0
plugin installed.

But I do recall that the error referred to a symbol that obs-websocket.so
needed but the OS libraries did not supply. My research indicated that
others were having the same problem with other products and it came down to
the code being compiled for the latest MacOS version which provided this
symbol but earlier versions did not. The symbol name began with two
underbars and included either the word "thread" or "stack" in it - but so
far I can't find the details. I'll continue to search back.

**Comment by tt2468** [comment]
Ah yeah that's unfortunately an issue with 4.9.1. We'll make sure it doesn't happen in 5.0.0
