### ISSUE TITLE
Feature reguest: Audiometer reguest (see incoming signal)

### ISSUE THREAD

**Issue by jeremiasmanninen** [obsproject/obs-websocket#855]
##### Issue type
Feature reguest

##### Description
Ability to get audiometer signal status as requested. For specific audio devices and/or the main output. Signal peak or current signal strength (-dB). Would help to monitor audio levels over the network. Mixing is easier when you see the strength of the signal. If it is possible sending a value as the incoming signal changes (all the time) would be great. Not sure how often it is possible to get new value but pretty often would be great so it looks natural audio signal meter.

##### Development Environment
Using with TouchOSC via OSC for OBS and that relays on OBS-WebSocket.

**Comment by tt2468** [comment]
Planned for 5.0.0
