### ISSUE TITLE
Feature Request: Open Source Properties

### ISSUE THREAD

**Issue by bryce-seifert** [obsproject/obs-websocket#864]
### Feature Request Type

RPC Request

### Requested Feature

OpenSourceProperties request, with the source as the variable.

Available in the [OBS API ](https://obsproject.com/docs/reference-frontend-api.html#c.obs_frontend_open_properties)as:
`void *obs_frontend_open_properties(obs_source_t *source)`

### Requested Feature Usage Scenario

Allow easy one click access to source properties, especially when sources aren't in the current scene.

**Comment by tt2468** [comment]
I definitely see the need for requests like this, as having this ability would definitely expand obs-websocket's ability to be used for hotkeys. Merging this request with #846.
