### ISSUE TITLE
Bug: after downloading obs-websocket and seeing it in tools, still unable to connect deckboard with obs

### ISSUE THREAD

**Issue by CherriBearxx** [obsproject/obs-websocket#865]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/W4ouJEWxeRgTNJGH

### Expected Behavior

To have Deckboard and OBS connect either automatically or by manually clicking 'connect to OBS'

### Current Behavior

Unable to connect Deckbaord to OBS even after following instructions from https://github.com/rivafarabi/deckboard/wiki/OBS-Studio-Setup

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

I have tried typing the port numbers manually both in OBS and in deckboard, I have tried using a password, I have tried uninstalling and reinstalling I have tried running both programs as administrator and still nothing allows them to connect. I can connect Deckboard to my android device but cannot connect it to my OBS software that is on the same computer. Ihave attached some images in the word doc showing some of the issue
[OBS and Deckboard issue.docx](https://github.com/obsproject/obs-websocket/files/7597508/OBS.and.Deckboard.issue.docx)
r.

**Comment by tt2468** [comment]
Closing this as it's not really a bug report. If you still need support, please use the discord.
