### ISSUE TITLE
Bug: StartStreaming command doesn't start stream

### ISSUE THREAD

**Issue by avivbeeri** [obsproject/obs-websocket#866]
### Operating System Info

macOS 11.6

### OBS Studio Version

27.1.3

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/JmiMB8YO6XhZi_po

### Expected Behavior

The stream should start, when using the "StartStreaming" websocket command.

### Current Behavior

What seems to happen is that OBS will try to connect to the server briefly, and then stop, with an error like "Could not connect to server" or "Stream key was inaccessible".

Occasionally, the connection will just hang instead, with the "stream" button in a perpetual "connecting" state until it times out.

Manually clicking the "Start Streaming" button works without issue.

### Steps to Reproduce

1. Install OBS and obs-websockets.
2. Use an external websocket client to send a StartStreaming command.
3. Observe the stream not starting.

### Anything else we should know?

I'm sending commands using obs-websockets-js.

**Comment by tt2468** [comment]
Unfortunately we are not supporting 4.x versions any longer, sorry about that.
