### ISSUE TITLE
Bug: Media time remaining variable doesn't work with playlist (VLC Video Source)

### ISSUE THREAD

**Issue by DachsbauTV** [obsproject/obs-websocket#872]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### obs-websocket Version

4.9.1

### OBS Studio Log URL

...

### Expected Behavior

Shows time remaining, either from the current element in the playlist or the remaining duration of the whole playlist

### Current Behavior

it shows 24:00:00 at the beginning of every media file

### Steps to Reproduce

1. create playlist
2. create button in companion with the time-remaining variable

**Comment by tt2468** [comment]
Unfortunately we aren't supporting 4.x versions anymore, sorry about that.

**Comment by DachsbauTV** [comment]
Ok  no worries, i'll give it a try with 5.0.0 as soon as it's ready
