### ISSUE TITLE
Feature Request: WAN Conection

### ISSUE THREAD

**Issue by CarlosGTI001** [obsproject/obs-websocket#886]
### Feature Request Type

RPC Request

### Feature Request Type (Other)

Conection

### Requested Feature

It would be possible, that is added in the type of connection, that it is possible to use the Wan network (Internet) to connect to the servers, from remote clients, without having to be in the same LAN network. It would be a very useful function.

### Requested Feature Usage Scenario

It would be useful in cases where the streaming is done on servers such as VPS, where managing the obs is usually complicated in case of not having a good internet connection.

**Comment by tt2468** [comment]
This is all networking related, not in the scope of obs-websocket. If you're using a VPS, you'd just have to configure the appropriate firewalling depending on how your machine's network is configured. On a home connection, you'd just need to port forward.

**Comment by CarlosGTI001** [comment]
Thanks for answering.
Yes, I have opened the ports and I have verified that the port is open, but, I have tried with several clients and it does not work.
