### ISSUE TITLE
Bug: Websocket 4.9.1 still crashing OBS when using Companion 2.2.x

### ISSUE THREAD

**Issue by BigJinge** [obsproject/obs-websocket#887]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/z9dqdT05NfLMKcef

### OBS Studio Crash Log URL

https://obsproject.com/logs/kU4kdcfkDBE3rEL_

### Expected Behavior

OBS should liase with Websocket for a clean shutdown of OBS. 

### Current Behavior

OBS hangs, shows unresponsive in window header then crashes. You either get an "OBS has crashed" message or an exe crash message. 

![OBS_Crash_1](https://user-images.githubusercontent.com/19828427/147800217-1adc7ef3-cc5b-4962-b3f5-7f05c9fd3de0.PNG)
![OBS_Crash_2](https://user-images.githubusercontent.com/19828427/147800218-f40de10e-0646-413e-a023-08e9309684d5.PNG)

This issue was supposed to have been fixed with 4.9.1 ([see this ticket](https://github.com/bitfocus/companion-module-obs-studio/issues/52)) when using 2.2.x betas of Companion but it is still happening.

Whilst the OBS URL to the crash log has been submitted, the crashed thread is shown below.

Thanks

`Thread E3D8: (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
0000004880DFF100 00007FFEFF312FD0 000001E833AB8A20 000001E8313B8F90 000001E831B4F2E0 0000000000000000 obs.dll!signal_handler_disconnect+0x50
0000004880DFF140 00007FFEF7A02FDA 000001E82CC0C270 00007FFF66CE3187 000001E831B4F2E0 0000004880DFF6C8 obs-websocket.dll!WSEvents::disconnectSourceSignals+0x3a
0000004880DFF170 00007FFEF7A0146A 000001E831B4F2E0 000001E82CC0C270 0000000000000000 000001E82430D820 obs-websocket.dll!WSEvents::OnSourceDestroy+0x4a
0000004880DFF1B0 00007FFEFF313312 0000004800000000 00007FFEFF39E4A8 0000004880DFF238 000001E831B4F2E0 obs.dll!signal_handler_signal+0x102
0000004880DFF210 00007FFEFF34E6B5 0000000000000000 000001E831708870 000000000000040D 00000000FFFFFFFF obs.dll!obs_source_destroy+0x1e5
0000004880DFF310 00007FFEFF352A3F 00007FFEFD17C928 00007FFEFD17C928 000000000000040D 000000000000040D obs.dll!obs_source_release+0x4f
0000004880DFF340 00007FFEFCE12195 0000004880DFF430 000000000000040D 000001E834366880 000000000000008D qt5core.dll!0x7ffefce12195
0000004880DFF380 00007FFEFCE126BC 0000000000000000 00007FFE0000040D 0000000000000000 00007FFF7C13FDE6 qt5core.dll!0x7ffefce126bc
0000004880DFF3B0 00007FFEFCE36443 0000004880DFF430 0000000000000000 0000000000000000 00007FFF7C1528E9 qt5core.dll!0x7ffefce36443
0000004880DFF3E0 00007FFEFCE3B7BB 0000004880DFF5A0 0000000000000000 0000004880DFF708 0000004880DFF6E8 qt5core.dll!0x7ffefce3b7bb
0000004880DFF410 00007FF6B996B65F 0000000000000000 0000004880DFF5A0 0000004880DFF5A0 0000000000000000 obs64.exe!OBSStudioAPI::obs_frontend_get_scenes+0xef
0000004880DFF460 00007FFEF7A0672D 0000004880DFF5A0 0000004880DFF5A0 0000000000000000 00007FFEF79E48E2 obs-websocket.dll!Utils::GetScenes+0x2d
0000004880DFF4B0 00007FFEF79E9961 0000004880DFF5A0 0000000000000000 0000004880DFF609 00007FFEF7A08578 obs-websocket.dll!WSRequestHandler::GetSceneList+0x41
0000004880DFF500 00007FFEF79E4B05 0000000000000004 0000004880DFF609 000001E83D886A20 000001E83D886920 obs-websocket.dll!WSRequestHandler::processRequest+0x115
0000004880DFF560 00007FFEF7A0945C 000001E83D8E7F90 0000004880DFF719 000001E83462DCA0 000001E83D8E7F90 obs-websocket.dll!OBSRemoteProtocol::processMessage+0x2dc
0000004880DFF670 00007FFEF79A9106 000001E834253600 000001E83D8E7F70 0000000000000001 000001E83D8E7F80 obs-websocket.dll!<lambda_87a16e3ae6535eb4d8b546915b5fa9d8>::operator()+0xe6
0000004880DFF780 00007FFEF79DA621 000001E83D8E7F80 000001E83D8E7F70 000001E8311E7480 0000000000000000 obs-websocket.dll!QtConcurrent::RunFunctionTask<void>::run+0x41
0000004880DFF7E0 00007FFEFCC5929E 000001E834253600 000001E8311E74D8 000001E834253600 000001E8342BA988 qt5core.dll!0x7ffefcc5929e
0000004880DFF870 00007FFEFCC55FF1 0000000000000000 0000000000000000 0000000000000000 0000000000000000 qt5core.dll!0x7ffefcc55ff1
0000004880DFF8A0 00007FFF7E6B7034 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7fff7e6b7034
0000004880DFF8D0 00007FFF7E802651 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7fff7e802651`

### Steps to Reproduce

1. On Windows 10 x64 21H1, install OBS 27.1.3 , Websocket 4.9.1 , Companion 2.2.x beta (version tested 2.2.0-5e326f35-3639)
2. With Websocket running and a Companion button created using the Companion obs module, start OBS.
3. Wait 30 secs.
4. Close OBS

OBS should crash with one of the error windows above.
...

**Comment by tt2468** [comment]
Replied over at bitfocus/companion-module-obs-studio/issues/52
