### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by bogorad** [obsproject/obs-websocket#890]
### Feature Request Type

RPC Event

### Requested Feature

I wonder if OBS "knows" when a client has connected to the new VirtualCam interface (and disconnected). So two events like:

- VirtualCamClientConnected
- VirtualCamClientDisconnected

and a request like 

- isVirtualCamClientConnected

### Requested Feature Usage Scenario

I'd like to power up my HDMI->usb3 camera when someone connects to the VirtualCam, and power it down when it disconnects.

**Comment by tt2468** [comment]
Unfortunately something like this is not realistically possible.
