### ISSUE TITLE
Bug: HotKeyByName fails to unpause, puasing works fine though.

### ISSUE THREAD

**Issue by thatmounaim** [obsproject/obs-websocket#891]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/2kHjUUmcwb1cDd0y

### Expected Behavior

Unpausing the paused recording after TriggerHotkeyByName with name equals to OBSBasic.UnpauseRecording

### Current Behavior

Not unpausing the recording when TriggerHotkeyByName with name equals to OBSBasic.UnpauseRecording

Request >> '{"hotkeyName":"OBSBasic.UnpauseRecording","request-type":"TriggerHotkeyByName","message-id":"56"}'

### Steps to Reproduce

1. Do a hotKeyTriggerByName
2. Name of the hotkey = OBSBasic.UnpauseRecording
3. Nothing Happens
...

### Anything else we should know?

OBSBasic.PauseRecording works just fine.

**Comment by tt2468** [comment]
Sorry, but we are no longer working on non-security updates for 4.x versions.
