### ISSUE TITLE
Bug: Switching scene collections with WebSocket installed causes intermittent crashes

### ISSUE THREAD

**Issue by tomhillmeyer** [obsproject/obs-websocket#894]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/FN5g2A0AD62keEP1

### Expected Behavior

Scene collection picker to be able to successfully switch between scene collections in OBS

### Current Behavior

OBS crashes with a memory error some of the time. After a reboot, switching scene collections usually works for a while but not always. 

### Steps to Reproduce

1. Have WebSokets installed and enabled
2. Attempt to switch between scene collections

### Anything else we should know?

Occurs on several different systems that have the latest versions of OBS and WebScokets installed. Issue goes away once WebSockets is uninstalled from the system.

**Comment by tt2468** [comment]
This is the result of polling operations (specifically GetSceneList) being performed while OBS is in an undefined state (mid-switch). Unfortunately, there's no good way for us to solve this problem on the obs-websocket side.

The solution we recommend to developers is to take advantage of the `SceneCollectionChanging` event in the new 5.x versions, and pause polling until the `SceneCollectionChanged` event has been received.

**Comment by eric** [comment]
Does this need a fix in OBS like obsproject/obs-studio#6597? If I recall correctly `GetSceneList` touches QT objects as well?
