### ISSUE TITLE
Bug: SetProfileParameter not working properly

### ISSUE THREAD

**Issue by nilp0inter** [obsproject/obs-websocket#895]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### obs-websocket Version

5.0.0-alpha3

### OBS Studio Log URL

https://obsproject.com/logs/7G8BWRMMQ02Hb8ao

### Expected Behavior

I expect the value of the parameters I set to remain set and not get reset to the defaults

### Current Behavior

The values of the parameter profile get reset when you change to another profile.

### Steps to Reproduce

1. Create a new profile
2. Set some parameters
3. Change to another profile
4. Change back to the profile you created
5. Request the value of the parameters you set

### Anything else we should know?

I tried to manually export the profile and the resulting .ini file is almost empty.

But if you open the settings menu between steps (2) and (3) and hit OK then the values remain set.

**Comment by tt2468** [comment]
Seems we forgot to save the profile after setting the parameter. Can you try reproducing this again but between steps 2 and 3 change and apply a setting through the OBS settings dialog? That should perform an apply operation, saving all pending changes.

**Comment by nilp0inter** [comment]
Yes, If I do that everything works just fine.
