### ISSUE TITLE
Feature Request: Reverse Connection

### ISSUE THREAD

**Issue by fGeorjje** [obsproject/obs-websocket#902]
### Feature Request Type

Other

### Feature Request Type (Other)

Reverse Connection

### Requested Feature

A configuration option to have obs-websocket establish a connection to an existing websocket server, instead of hosting a local server on the user machine.

### Requested Feature Usage Scenario

I run production for a fully remotely streamed charity fundraising event. We distribute portable-mode OBS instances to our talent containing obs-websocket, but because the plugin hosts itself locally on the client machine, we have to jump through hoops (distributing an [entirely separate application](https://github.com/NoGlitchesAllowed/obs-link) and launching it along OBS) to get bidirectional connections established.

Setting up port forwarding for 100+ talents during tech checks is not feasible, the connection must be established from the client machine. Having the plugin connect itself would cut out the middle proxy.

**Comment by tt2468** [comment]
A client mode has been attempted multiple times in the past, at various stages of obs-websocket's development. Unfortunately, supporting both a client and a server mode has proven overly difficult to implement.

One idea could be to use a python script in obs-scripting to connect to obs-websocket, and then connect to your own hosted websocket and forward messages back and forth. That way you can at least keep everything contained within OBS (no dedicated processes)
