### ISSUE TITLE
Bug: OBS (SE.live build 27.1.3) crashes at start

### ISSUE THREAD

**Issue by Glucksbar** [obsproject/obs-websocket#905]
### Operating System Info

Other

### Other OS

Mac OS 12.1

### OBS Studio Version

27.1.3

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/y20Wfm7bitYbOR4L

### Expected Behavior

I got a Loupedeck live. To use it with OBS I need to install the websocket Plugin. Well, at least, if I don't want to set all hotkeys in obs and macro them manually to Loupedeck.

Expected behaviour is, that I install the websocket Plugin and run OBS.

### Current Behavior

I installed the websocket Plugin. I used the provided installer, didn't compile it myself, as I don't know how to do that.
I start SE.live and it immediately crashes.
The moment, I delete the websocket folder from Application Support, it runs again.

Since I don't know, if my log-report was correct, here is the "crash-log"
[2022-02-03 09-41-13.txt](https://github.com/obsproject/obs-websocket/files/7993040/2022-02-03.09-41-13.txt)
.

### Steps to Reproduce

1.
2.
3.
...

**Comment by tt2468** [comment]
This is an issue with Loupdeck's plugin interfering with ours. If you are already on the latest version of loupdeck-obs, you will need to wait for them to release a new one before using the two plugins together.
