### ISSUE TITLE
Bug: Removeinput is throwing error

### ISSUE THREAD

**Issue by umens** [obsproject/obs-websocket#912]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0 (x64)

### obs-websocket Version

5.0.0-alpha3

### OBS Studio Log URL

https://obsproject.com/logs/8G2OLA-Y6dKfnU2j

### Expected Behavior

RemoveInput should be available (cf [Protocol.md](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#removeinput))
 

### Current Behavior

RemoveInput request is throwing an error saying it is not available => RequestStatus::UnknownRequestType
GetVersion request shows that 'RemoveInput' is not in 'availableRequests'

### Steps to Reproduce

1. fresh install & start obs with the plugin installed
2. go to [codesandbox](https://codesandbox.io/s/heuristic-brook-hb5qh4?file=/src/index.js)

**Comment by tt2468** [comment]
The RemoveInput request was not enabled in 5.0.0-alpha3 as it required changes made to OBS that were pending release (27.2): https://github.com/obsproject/obs-websocket/commit/1f1a8926b180aa0beb7ab21e02e28b600b4f7358

To use that request, you'll need to use our nightly or wait the next few days for 5.0.0-beta1.
