### ISSUE TITLE
Bug: Unable to build 4.9.1 against obs-studio 27.2.0 headers

### ISSUE THREAD

**Issue by yhtez** [obsproject/obs-websocket#916]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0

### obs-websocket Version

4.9.1

### OBS Studio Log URL

N/A

### Expected Behavior

obs-websocket to successfully build with obs-studio 27.2.0 headers

### Current Behavior

obs-websocket fails to build due to conflicting and incompatible OBSRefAutoRelease definitions in obs.hpp (adding an #ifndef guard isn't sufficient to fix)

### Steps to Reproduce

1. Install obs-studio 27.2.0
2. Attempt to build obs-websocket 4.9.1 against headers from installed obs-studio
3. Fails to build due to libobs header incompatibilities

**Comment by tt2468** [comment]
This is a known problem. You will need to build against 27.1.3.

**Comment by BtbN** [comment]
Run `sed -r -i 's/OBS(.+?)AutoRelease/OBS\1AutoRelease_OBSWS/g' src/*.h src/*/*.h src/*.cpp src/*/*.cpp` to fix the issue.
This still affects the compat branch, so it's rather annoying when packaging.
