### ISSUE TITLE
Feature Request: Add to CallVendorRequest Response "requestType" and "vendorName"

### ISSUE THREAD

**Issue by lemolok** [obsproject/obs-websocket#919]
### Feature Request Type

RPC Request

### Feature Request Type (Other)

CallVendorRequest

### Requested Feature

Add after `responseData["responseData"] = Utils::Json::ObsDataToJson(obsResponseData)`

responseData["requestType"] = requestType;
responseData["vendorName"] = vendorName;

### Requested Feature Usage Scenario

To know which vendor responds with which request.
It can be useful in the case of several vendor plugins.
As for vendor events ("eventType", "vendorName", "eventData")

**Comment by tt2468** [comment]
What is an example of a case where the context of the original request is not held? Wouldn't you know this information from the original request?
