### ISSUE TITLE
Bug: Cannot connect to Websocket on 5.0.0-beta1 Mac build

### ISSUE THREAD

**Issue by felippenardi** [obsproject/obs-websocket#922]
### Operating System Info

macOS 12.0

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.1

### obs-websocket Version

5.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/KHIbjeORMLb-mS9t

### Expected Behavior

Running this would connect successfully to the new websocket

```js
const OBSWebSocket = require("obs-websocket-js");

const obs = new OBSWebSocket();

obs
.connect({
  address: "127.0.0.1:4455"
})
.then(
    () => {
        console.log({ log: 'Connected to OBS successfully' });
    },
    (error) => {
      console.log(error)
    }
);
```

And I have it setup properly:

<img width="787" alt="CleanShot 2022-03-10 at 20 39 01@2x" src="https://user-images.githubusercontent.com/1354492/157773771-5242a951-f818-4fa2-91fa-f169adc40be9.png">

### Current Behavior

The promise never resolves when the OBS is running. As soon as I close, it returns the error.

### Steps to Reproduce

1. Download the Mac build of obs-websocket 5.0.0-beta1
2. Disable password
3. Try to connect to port 4455
4. You will see it will not work
...

**Comment by tt2468** [comment]
`20:36:11.934: [obs-websocket] [WebSocketServer::onMessage] Client 127.0.0.1:53141 appears to be running a pre-5.0.0 protocol.`

You are connecting to obs-websocket v5 (new protocol) using a 4.x client. You'll want to connect to 4.9.1-compat with your client or use a newer version of obs-websocket-js.

**Comment by felippenardi** [comment]
Thank you!!
