### ISSUE TITLE
Bug: 'from-scene' field is sometimes absent in response message from TransitionBegin. 

### ISSUE THREAD

**Issue by millerdq** [obsproject/obs-websocket#926]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.3

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/LvyirVLZr7ljvc93

### Expected Behavior

TransitionBegin response should include the 'from-scene' item. 

### Current Behavior

Sometimes the 'from-scene' is missing from the TransitionBegin response message.  The problem occurs when NOT in studio mode, when a transition is started by clicking on the Scene name before the prior transition finishes (i.e. long transition duration), and when the to-scene does not contain any sources.

Screenshot is a from an html browser dock that connects to websockets with javascript.  

![2022-03-26](https://user-images.githubusercontent.com/18232452/160262306-90b6957a-6bcc-4be4-8b5a-db904f767612.png)

### Steps to Reproduce

1.  Turn off studio mode
2.  Set a long-ish transition duration -- 2 seconds, for example
3.  Initiate two scene changes in quick succession
4.  Repeat until problem occurs, as it is intermittent

**Comment by tt2468** [comment]
Sorry, but we are no longer doing non-security updates for 4.x versions.
