### ISSUE TITLE
Building on Windows not working

### ISSUE THREAD

**Issue by coccoalberto97** [obsproject/obs-websocket#927]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/OfqiHrSBRuAODtRH

### Expected Behavior

Being able to build the plugin on windows with CMake.

### Current Behavior

The plugin is not building on Windows, CMake can't find LIBOBS_LIB LIBOBS_INCLUDE_DIR

`Could NOT find Libobs (missing: LIBOBS_LIB LIBOBS_INCLUDE_DIR) 
CMake Error at external/FindLibObs.cmake:106 (message):
  Could not find the libobs library
Call Stack (most recent call first):
  CMakeLists.txt:19 (include)`

![image](https://user-images.githubusercontent.com/30443179/160361127-4a47e91d-17b3-4f8d-a09f-4259ba42618e.png)
![image](https://user-images.githubusercontent.com/30443179/160361308-45cb33cb-0839-4b8e-a5f7-542382f33c31.png)

### Steps to Reproduce

1. Download Obs Studio 27.1.3 Source code (https://github.com/obsproject/obs-studio/releases/tag/27.1.3)
2. Build Obs Studio 27.1.3 with cmake
3. Download Obs Websocket 4.9.1 Source code (https://github.com/obsproject/obs-websocket/releases/tag/4.9.1)
4 Follow BUILDING.md Windows section
5 Configure with Cmake.

**Comment by tt2468** [comment]
Please use the Discord for support-related issues.
