### ISSUE TITLE
Bug: Wrong guess for IP addresses (QR code)

### ISSUE THREAD

**Issue by malliaridis** [obsproject/obs-websocket#928]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.4

### obs-websocket Version

5.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/yVBYdt9pPcewO7OY

### Expected Behavior

It is expected that OBS Studio makes the correct guess or provide every possible IP address in the QR code.

### Current Behavior

The OBS Studio is guessing as IP address the address of the wrong network adapter. This makes the QR code unusable, since it provides only one address.

### Steps to Reproduce

1. Have multiple network adapters active (with addresses e.g. 192.168.56.1 (virtual box) and 192.168.178.23 (home network))
2. Open the Settings dialog
3. See the IP address guessed (the virtual box address)

### Anything else we should know?

As a solution it would require different QR code generation. Streamlabs OBS provides multiple addresses as a query parameter in the URL. The content looks as follow (decoded):
```
https://streamlabs.page.link/
    ?link=https://streamlabs.com/mobile-app
    &data={
        "addresses": ["[IPv6-Addresss]","192.168.56.1","[Another-IPv6-Address","[One-More-IPv6-Address]","192.168.178.23"],
        "token":"[API-TOKEN]",
        "port":59650,
        "version":"1.7.1"
    }
    &apn=com.streamlabs.slobsrc
    &isi=[SOME_NUMBER]
    &ibi=com.streamlabs.slobsrc
    &utm_source=slobs
```

The approach of providing multiple addresses allows to filter those by network mask. It also allows to later add more information, like proxies and metadata.

This issue could also be a feature request for extending the provided addresses.

**Comment by tt2468** [comment]
After some thought, I decided to just ignore the default VirtualBox IP subnet. The SLOBS format is arguably more "reliable", but we're simply trying to give developers an easy-to-implement format while suiting at least most of our users, which I think the current system accomplishes. Not against revisiting it in the future, but I think we should see first how the current system works before trying to rethink it again.

**Comment by malliaridis** [comment]
That makes totally sense. This part is critical and changing it should be considered with care. Leaving it as it is right now is probably the best we could do.
I've got some migration ideas in case this turns out to be a problem in the future. I'll be happy to discuss those if that moment comes. :)

**Comment by tt2468** [comment]
Make sure to join the Discord server if you can, that's where we discuss most changes and new features

**Comment by BuyMyMojo** [comment]
Issue still occurs, binds to Windows Subsystem for Linux's Hyper-V adapter, completely unusuable while it's bound to this

**Comment by BuyMyMojo** [comment]
The IP adress for that is 172.17.128.1
