### ISSUE TITLE
Bug: VirtualCam requests return 'request type not valid'

### ISSUE THREAD

**Issue by hlb18** [obsproject/obs-websocket#933]
### Operating System Info

Ubuntu 18.04

### OBS Studio Version

27.1.3

### obs-websocket Version

5.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/PZm1Rp5fsKWNzA_T

### Expected Behavior

StartVirtualCam/StopVirtualCam to be actioned
GetVirtulCamStatus to return current status

### Current Behavior

All return 'Your request type is not valid'

### Steps to Reproduce

1. Connect to OBS
2. Send StartVirtualCam/StopVirtualCam/GetVirtualCamStatus
3.
...

**Comment by pruje** [comment]
I can confirm this bug occurs also on Ubuntu 22.04 beta

**Comment by tt2468** [comment]
According to your OBS log, OBS is loading with `5.0.0-alpha3`, which did not yet include those requests. Making sure OBS uses 5.0.0-beta1 should fix that issue.
