### ISSUE TITLE
Feature Request: Emit record filename like `ReplayBufferSaved`

### ISSUE THREAD

**Issue by chenxiao1990** [obsproject/obs-websocket#934]
### Feature Request Type

RPC Request

### Requested Feature

add record filename  to StopRecord request.

### Requested Feature Usage Scenario

when record down, i  will upload file to  server, but  i can't get filename .  
because i can't make sure  my ws-client localtime  is  equal to  obs-studio time,  i can't use  filename format to general record filename.

**Comment by tt2468** [comment]
Will work on this at some point.

Note to me: <https://github.com/obsproject/obs-websocket/blob/4.x-current/src/Utils.cpp#L718>

**Comment by ArekMC** [comment]
Same issue here. I need to copy the recorded files, which worked great with 4.9.
