### ISSUE TITLE
Bug: GetGroupItemList - your request type is not valid

### ISSUE THREAD

**Issue by eltharynd** [obsproject/obs-websocket#936]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

26.2.4 (64 bit)

### obs-websocket Version

5.0.0-beta1

### OBS Studio Log URL

none

### OBS Studio Crash Log URL

none

### Expected Behavior

GetGroupItemList should return the list of items inside a group

### Current Behavior

GetGroupItemList returns a "your request type is not valid" error

### Steps to Reproduce

try calling GetGroupItemList

**Comment by tt2468** [comment]
Please provide an OBS studio log as requested by the issue template.

**Comment by eltharynd** [comment]
There's no need for logs... the request just simply isn't there...

Anyways i figured it out.. in release notes it says GetGroupSceneItemList was implemented, but that reqwuest type does not exist in documentation (and is actually GetGroupItemList in docs)
