### ISSUE TITLE
Feature Request: SetTextGDIPlusProperties

### ISSUE THREAD

**Issue by pbuchi2000-adiacom** [obsproject/obs-websocket#939]
### Feature Request Type

RPC Request

### Requested Feature

Could you please add support for setting GDI+ texts. In the previous version it was called SetTextGDIPlusProperties

### Requested Feature Usage Scenario

We want to have a bottom bar that would show things like a speaker's name, similar to what they often have in the news

**Comment by tt2468** [comment]
That request in 4.x was simply a shortcut of SetSourceSettings. In 5.x, use `SetInputSettings`. You can get the field names for the GDI text input via GetInputSettings or GetInputDefaultSettings.

**Comment by pbuchi2000-adiacom** [comment]
Thank you
