### ISSUE TITLE
Bug: Request without requestType causes a OBS Crash

### ISSUE THREAD

**Issue by EroAxe** [obsproject/obs-websocket#942]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### obs-websocket Version

5.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/RqYzMtXEumlI5zP7

### OBS Studio Crash Log URL

https://obsproject.com/logs/tpuDdU29N39GSgk4

### Expected Behavior

My assumption would have been to get an error back rather than a full program crash.

### Current Behavior

The program instantly froze and crashed.  Interrupting any ongoing stream and completely blocking switching to it in any way.

### Steps to Reproduce

1. Connect
2. Send a Request without "requestType"
3. Instant Freeze/Crash

**Comment by tt2468** [comment]
Would you be able to post a log with debug logging enabled?
