### ISSUE TITLE
Bug: Obs WebSocket Plugin not working.

### ISSUE THREAD

**Issue by WinGamingPT** [obsproject/obs-websocket#950]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/L5bUjqgbHUE0SE-e

### Expected Behavior

It was expected after installing for the plugin to appear on OBS. 

### Current Behavior

It didn't  work as intended no matter the way it was installed. 

### Steps to Reproduce

1.Install OBS in non disk C:
2. Install plugin(either being by installer or zip file)
3. Voillá its reproduced

### Anything else we should know?

It was tried everything (besides installing OBS on windows' drive due to lack of space), from installed and reinstalled the plugin with installer and zip with obs off, only having plugins file with socket plugin installed, to seeing the logs that showed that it wasnt loading with no apparent error as seen in the logs attacked to this issue report, and all files in the folder. No VPNS or external software were used that could interfer with something like this.

**Comment by tt2468** [comment]
This sounds like a support issue, and not a bug. Please use the Discord server for support.
