### ISSUE TITLE
Bug: OBS Websocket crached in Touch Portal and no communication

### ISSUE THREAD

**Issue by DanDu4** [obsproject/obs-websocket#953]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/tiEvoH8rSHN6z8q3

### Expected Behavior

Touch Portal was working fine yesterday.  I was able to mute mic audio, switch scenes and start/stop OBS recording. 

### Current Behavior

Touch Portal v3.0.11 is reporting OBS Websocket has crashed or OBS connection failed as the password is incorrect.  I am unable to copy the password from the Websocket Server Setting window to paste into the Touch Portal OBS settings and if I change the password it does not stay set to what I changed it to.  This was working fine yesterday.  Nothing seems to have changed so I don't know why its stopped working. 

### Steps to Reproduce

1.Launch OBS
2.Launch Touch Portal
3.Touch Portal reports "OBS Websocket crashed. Unfortunately Touch Portal has detected the OBS Websocket is crashed. This cannot be fixed at run time.  Please restart Touch Portal"
4. Touch Portal then reports "OBS Connection failed. OBS connection could not be set up because the credentials are not correct. Please verify you have used the same password in the Websocket settings in OBS (Tools->Websocket) and in Touch Portal (Settings->OBS).

I am unable to copy the password from the Websocket Sever Settings window to paste it to the Touch Portal settings page and the password does not stay if I change it. I have tried turning off the 

### Anything else we should know?

I am unable to copy the password from the Websocket Sever Settings window in OBS to paste it to the Touch Portal settings page and the password does not stay if I change it. I have tried turning off the Authentication and deleting the password.  I have reinstalled the plug in into the OBS directory folder both using the EXE file and manually saving the files from the ZIP folder.  It was working fine and I cant work out what's changed. When I installed it originally I was able to copy the password from the window in OBS to the Touch Portal settings window but it just wont let me. Please help? Its such a great feature and I love using it! 
![image](https://user-images.githubusercontent.com/107963589/174915023-aa8c2cb3-7afa-4b77-aea6-f8c5b7ab7f5a.png)
![Touch Portal Error Messages](https://user-images.githubusercontent.com/107963589/174915288-90238eea-c5b3-40c8-a2fe-9e59e14d5c86.jpg)

**Comment by tt2468** [comment]
Please post a log with debug mode enabled. Is OBS actually crashing when touch portal says it is? If obs-websocket 'crashes', all of OBS will.

In terms of passwords, you can't copy the WebSocket password because it is not retrievable after you set it. The number of dots it shows you is always constant regardless of the real password length. This is how password dialogs usually work in UIs. You should make a password, then paste it into obs-websocket and touch portal.

**Comment by DanDu4** [comment]
Hi tt2468,  OBS is not actually crashing at all, its still running fine. I have tried setting the password on both Touch Portal and the WebSocket Server Settings window but still get the same issue. Touch portal just keeps saying the password is incorrect even though I know its right. I've tried setting them, shutting each program down, restarting the PC then launching each one again and the same thing. How do I post a log with debug enabled and if OBS is working fine do you still need it?

**Comment by DanDu4** [comment]
Hi tt2468 After spending 3 hours trying all sorts to get it working its suddenly started working again! No idea why.  I thank you for your response though. It was much appreciated.

**Comment by tt2468** [comment]
Very odd. Glad you got it sorted! obs-websocket 5.0.0 will be releasing soon that has many usage improvements like copyable passwords. Not sure if touch portal has support for it yet but it will be very good when it does.
