### ISSUE TITLE
Bug: GetGroupSceneItemList and GetSceneItemList returns scene items in reverse

### ISSUE THREAD

**Issue by majorofxd** [obsproject/obs-websocket#955]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### obs-websocket Version

5.0.0-beta1

### OBS Studio Log URL

n/a

### Expected Behavior

On successful response, it would return an object containing the property `sceneItems`, which is an array of items ("Sources" in the OBS GUI) in the order which they are arranged in the GUI, from top to bottom. 

### Current Behavior

The `sceneItems` listed the items in reverse, that is, from bottom to top.

Same issue arise when calling "GetSceneList", where the scenes are listed in reverse.

### Steps to Reproduce

1. Connect to the websocket using obs-websocket-js
2. ws.call('GetSceneItemList', { sceneName: desiredSceneName }).then( $result => console.log( $result ) )

### Anything else we should know?

I'm using [obs-websocket-js](https://github.com/obs-websocket-community-projects/obs-websocket-js) 5.0.0-beta.2. Also notifying them of the bug in case such issue was on their side.

**Comment by tt2468** [comment]
Array items in 5.x are meant to be returned bottom to top, as the bottom layer signifies layer 0 in things like a scene item stack.
