### ISSUE TITLE
Feature Request: Source Creation and Property Setting

### ISSUE THREAD

**Issue by GeorgesOatesLarsen** [obsproject/obs-websocket#956]
### Feature Request Type

RPC Request

### Requested Feature

Requests to perform the following:
- Get a list of available source types
- Create a new source with a specific source types
- Get a list of properties and property types of a source
- Get/set the value of a source property
- Delete a source

### Requested Feature Usage Scenario

Primary use case, here, is dynamically / auto-generated scenes. For instance, using an external layout-generation system.

In particular, the ability to dynamically generate mirror sources (from StreamFX) would be very useful to me, but dynamically generated scenes in general would benefit from these features.

**Comment by tt2468** [comment]
If you haven't seen the docs, I recommend giving them a read.

> Get a list of available source types

<https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getinputkindlist>


> Create a new source with a specific source types

<https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#createinput>


> Get a list of properties and property types of a source

This one isn't always reliable, but <https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getinputdefaultsettings>


> Get/set the value of a source property

<https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getinputsettings>
<https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#setinputsettings>


> Delete a source

<https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#removeinput>

**Comment by GeorgesOatesLarsen** [comment]
Are inputs the same as sources...? My understanding was that these were exclusively for audio inputs. Am I mistaken in that understanding? @tt2468

**Comment by tt2468** [comment]
There are 4 different types of "sources" in OBS, so to have predictable functionality, requests use the underlying type in the request name if the functionality is exclusive to that type. There are Inputs, Scenes, Transitions, and Filters. As such, Inputs are effectively what deliver external audio and video to OBS, like color, vlc, media, display capture, etc. Audio input capture is also a kind of input that only produces audio.

**Comment by GeorgesOatesLarsen** [comment]
I see, I apologize for my misunderstanding. Part of my confusion was the presence of such requests as "GetSourceActive" and "GetSourceScreenshot". I had assumed (back when I read the docs before raising this issue) that because some of the events referred to sources as "Sources", the events pertaining to "Input" were unrelated. I specifically conflated them with the audio inputs that I now see OBS does not even refer to as "Input".

I see what you mean now about filters, transitions and scenes also being sources in libobs.

Would you be open to adding a statement to the "Input" section that says something to this effect? Something like:

> NOTE: Internally, there are four types of sources in OBS: Input, Filter, Transition, and Scene. These requests regard the first type, Inputs, which the OBS-Studio UI informally refers to as "sources"

If a statement like that had been there, this silly issue would never have been raised by me

If you agree a statement like that makes sense, I'd be happy to do the leg-work and submit a PR myself.
