### ISSUE TITLE
Bug: can't install both 5.0.0 and 4.9.1-compat deb packages because they have the same name

### ISSUE THREAD

**Issue by ddan39** [obsproject/obs-websocket#959]
### Operating System Info

Ubuntu 20.04 LTS

### OBS Studio Version

27.2.4

### obs-websocket Version

5.0.0-beta1

### OBS Studio Log URL

N/A

### Expected Behavior

I can install both deb packages, probably one named obs-websocket and other obs-websocket-4.9.1-compat

### Current Behavior

They both try to install with the name obs-websocket, so only 1 can be installed at a time. The 2nd one to be installed will show as an upgrade or a downgrade.

### Steps to Reproduce

download both deb files, try to install them

**Comment by tt2468** [comment]
Fixed in https://github.com/obsproject/obs-websocket/commit/af1399e0051a0282709e0a393c0af213b58799c5 will update the binaries linked in the releases by the end of the day.
