### ISSUE TITLE
Bug: OBS soft locked

### ISSUE THREAD

**Issue by ODDdavidster** [obsproject/obs-websocket#962]
### Operating System Info

macOS 10.13

### OBS Studio Version

27.2.4

### obs-websocket Version

4.9.1

### OBS Studio Log URL

https://obsproject.com/logs/C7Y27nfLPdWsJRhH

### Expected Behavior

I Expected OBS to open and run with this plug in.

### Current Behavior

OBS wont open after the install 

### Steps to Reproduce

1.Download websocket and install
2.Quit OBS
3.Try to open OBS
4.Crash
...

### Anything else we should know?

Had to uninstall the plugin to fix this.

**Comment by tt2468** [comment]
Sorry, but we don't provide support for 4.x any longer. I've not seen this issue before though, so that's weird. You may want to try installing obs-websocket 5.0.0 and obs-websocket 4.9.1-compat on your system to see if the more recent binaries work better.
