### ISSUE TITLE
Bug: InputVolumeMeters event not getting hit

### ISSUE THREAD

**Issue by Mr-Mmhhmm** [obsproject/obs-websocket#970]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### obs-websocket Version

5.0.0

### OBS Studio Log URL

https://obsproject.com/logs/uLCymHYAQcfVgcTT

### Expected Behavior

Log input volume meter information every 50ms as per documentation.

### Current Behavior

Only logs connection info `{rpcVersion: 1, obsWebSocketVersion: '5.0.0', negotiatedRpcVersion: 1}`

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

```
const obs = new OBSWebSocket();

obs.connect(undefined, "asdf123").then((res) => {
	console.log(res);
}, (error) => {
	console.error(error);
});

obs.on("InputVolumeMeters", (data) => {
	console.log(data);
});
```

**Comment by tt2468** [comment]
You must subscribe to the InputVolumeMeters event intent using whatever method your obs-websocket client provides in order to receive the event, as it's considered high-volume.
