### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by nicnacnic** [obsproject/obs-websocket#972]
### Feature Request Type

RPC Request

### Requested Feature

A dedicated request to refresh a browser source. Currently, to do this, you need to use the `PressInputPropertiesButton` request with the propertyName `refreshnocache`. While this works, it's extremely hard to find the right property name to use, as it is not in the documentation. This request would simplify a heavily used feature in OBS.

### Requested Feature Usage Scenario

This request would be used to refresh a browser source.

**Comment by tt2468** [comment]
The idea behind this is to deduplicate the amount of requests we have in obs-websocket doing very similar logic. My plan is to supplement this ambiguous functionality with more documentation, in the form of a best practices document.
