### ISSUE TITLE
Bug: Loading failed at OBS 28.0.0-beta1

### ISSUE THREAD

**Issue by ZogeMung** [obsproject/obs-websocket#976]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0

### obs-websocket Version

5.0.0

### OBS Studio Log URL

https://obsproject.com/logs/ytnZcjv13FXeP_cY

### Expected Behavior

![image](https://user-images.githubusercontent.com/21040938/183474256-00432d60-c036-4d28-973a-e6717c6a6660.png)
This box won't appear or SPECIFIC LINE TEXT won't appear. 

### Current Behavior

![image](https://user-images.githubusercontent.com/21040938/183474458-de2ac5c5-1bad-44fb-9cad-1f62b7b41b1f.png)
Launch OBS Studio then show this box. 

### Steps to Reproduce

1. Install websocket
2. Launch OBS Studio 28.0.0-beta1
3.
...

### Anything else we should know?

Does OBS 28.0.0-beta1 using QT6 cause the problem?

**Comment by tt2468** [comment]
OBS v28 comes with obs-websocket 5.0.1 built-in. We will release Qt6-compatible 4.9.1-compat soon.
