### ISSUE TITLE
Feature Request: Support - even partial - for WS 4.9 in OBS 28

### ISSUE THREAD

**Issue by Rosuav** [obsproject/obs-websocket#982]
### Feature Request Type

Other

### Feature Request Type (Other)

Increased compatibility

### Requested Feature

The current protocol (v5) is incompatible with the older protocol, so any tools built to talk to OBS WebSocket v4.9 will simply not work on v5. This means that any tool not updated is fully broken, and it is difficult to make a tool that can work with both OBS 28 and OBS 27.

If it is at all possible to build OBS WebSocket v4.9 as a plugin for OBS 28, even if it isn't able to perform all operations, this would vastly improve backward compatibilty.

The main cost is Qt, as upgrading from Qt5 to Qt6 is inherent in the OBS 27 -> 28 migration. The easiest solution may be to avoid all Qt features from the WS functionality.

### Requested Feature Usage Scenario

The [OBS Tablet Remote](http://t2t2.github.io/obs-tablet-remote/) does not appear to have been updated for v5, and will not work with OBS 28. Even if it is, it would be difficult and inefficient to try to support both OBS 27 and OBS 28, so the remote control's author would have to choose between versions.

Rather than cause a massive Flag Day across the entire OBS WebSocket ecosystem, whereby new versions of every single app and tool must be deployed simultaneously with the OBS upgrade, it would be beneficial to offer at least some support for running OBS WS 4.9 inside OBS 28.

**Comment by tt2468** [comment]
Please refer to https://github.com/obsproject/obs-websocket/releases/tag/5.0.1

4.9.1-compat binaries will also be available for OBS 28. We have a download link to a signed binary in the beta-testing channel in the Discord, and will make a full release when it's ready.

**Comment by Rosuav** [comment]
Oh! I was trying to build it into my built-from-source OBS and it wasn't working. Are you using the 4.x-compat branch or 4.x-compat-new-cmake ? The first one didn't build, and the second one wasn't detected, so maybe I was just building it wrongly.
