### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by sellerscrisp** [obsproject/obs-websocket#985]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0

### OBS Studio Version (Other)

28.0.0-beta2

### obs-websocket Version

5.0.1

### OBS Studio Log URL

https://obsproject.com/logs/jq5iE5q0NZL0IvtY

### Expected Behavior

Expected obs-websocket to load. Plugin load error:
```
The following OBS plugins failed to load:

obs-websocket

Please update or remove these plugins.
```

### Current Behavior

obs-websocket didn't load.

### Steps to Reproduce

1. Clean install of OBS Studio 28.0.0-beta2.
2. Install obs-websocket 5.0.1 via installer or manually.
3. Run OBS Studio.

**Comment by tt2468** [comment]
OBS Studio v28 *comes with* obs-websocket 5.0.1. You will need to reinstall OBS v28 to fix the issue.

We note part of this in the 5.0.1 release page:
![image](https://user-images.githubusercontent.com/28720189/185278553-eb219087-f4a2-497e-bd79-22b7adbe3d91.png)
