### ISSUE TITLE
Feature Request: Prefix set request

### ISSUE THREAD

**Issue by jyapper0** [obsproject/obs-websocket#988]
### Feature Request Type

RPC Request

### Requested Feature

First, 
I thank all people who contributed to this excellent library and I apologize for my poor English.

In previous versions,  there was a SetFilenameFormatting request protocol but now there isn't.
I used it to divide output directories to each games or active window name.
I usually record by replay buffer, So I want Request protocol to **set prefix of filename**, please.

I'm also grad you'll restore **SetFilenameFormattin** again, of course.

### Requested Feature Usage Scenario

For example, when I set filename manually on OBS into "sub\%hh-%mm-%ss", obs make a sub directory "sub" on the output path automatically. This method works even setting prefix to "sub\".
I want to set this parameter via websocket. 

Again, I apologize for my poor English. If I don't inform you my intention, comment me, plz.

**Comment by jeiea** [comment]
I think `RecordStateChanged` is sufficient. It has `outputPath` field. If output file is recorded, you can rename that path file yourself. Replay buffer is same. So I think `SetRecordingFolder` is not good wrt minimality. I have also doubt every streamer accept easily their configuration changes.

If you still need old behavior I think you should wait compat library.

**Comment by jyapper0** [comment]
I had no idea moving file after saving.
Finally, I can make what I and friends need.
Thank you so much for telling it to me.
