### ISSUE TITLE
Bug: OBSWS 5.0 documentation error (Wrong response listed for 'SaveSourceScreenshot')

### ISSUE THREAD

**Issue by BeyondStreaming** [obsproject/obs-websocket#991]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### obs-websocket Version

5.0.1

### OBS Studio Log URL

none

### Expected Behavior

OBSWS 5 documentation shouldn't list a response parameter for 'SaveSourceScreenshot' (base64 string is only returned on 'GetSourceScreenshot'): https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#savesourcescreenshot

### Current Behavior

Documentation is wrong: https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#savesourcescreenshot

### Steps to Reproduce

Open the documentation: https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#savesourcescreenshot

**Comment by ChristopheCVB** [comment]
:+1: Maybe you can open a PR to resolve it?

**Comment by BOLL7708** [comment]
Glad to see this is already reported. I actually DO want the base64 data in the response, but I guess that is not going to change, and it is just the documentation that is wrong?
