### ISSUE TITLE
Bug: 4.9.1-compat is not compatible with OBS 28

### ISSUE THREAD

**Issue by josch700** [obsproject/obs-websocket#993]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### obs-websocket Version

5.0.1 / 4.9.1-compat

### OBS Studio Log URL

https://obsproject.com/logs/VPOjxCpFko9UZxhm

### Expected Behavior

Plugin can be loaded , even tho 5.0.1 can.

### Current Behavior

OBS can't load the plugin and deactivates it.

### Steps to Reproduce

1. Install OBS 28
2. Try to use 4.9.1-compat
3. Get the pop up it can't be loaded

**Comment by josch700** [comment]
Well just saw the new binaries. Thanks guys.

**Comment by oparada1988** [comment]
I know this issue is closed, but not to sound stupid how did you get it working? For me it doesnt show up under the tools menu. Just the built in one. I installed the lates binary on Ubuntu 22.04

**Comment by josch700** [comment]
You can download the compat version for OBS 28 here:
https://github.com/obsproject/obs-websocket/releases/tag/4.9.1-compat
But one thing, it seems like some tools that connect to the websocket have a scuffed version check. They say 4.9.1-compat had some breaking changes to 4.9.1 but it doesn't seem like it. Maybe someone here could confirm or deny that.

**Comment by tt2468** [comment]
4.9.1-compat does not have any breaking changes outside of returning `4.9.1-compat` as the plugin version instead of `4.9.1`.

**Comment by josch700** [comment]
It might be the better choice to maybe set the version to 4.10.0 or leave it at 4.9.1. I don't know how many tools will have problems but at least one that's used fairly often with a stream deck probably doesn't have a bullet proof version check. Not to mention that in this case the version check even is not SemVer compliant.

**Comment by josch700** [comment]
@tt2468 It might be the better choice to maybe set the version to 4.10.0 or leave it at 4.9.1. I don't know how many tools will have problems but at least one that's used fairly often with a stream deck probably doesn't have a bullet proof version check. Not to mention that in this case the version check even is not SemVer compliant.

**Comment by tt2468** [comment]
Bit too late for that, compat is already out. It's been available for v27 for months now.

**Comment by josch700** [comment]
Yeah I guess you have a point. Weird situation all in all. If this mentioned tool had a better version check it wouldn't have any problem and it might not be that big of an issue cause they are now porting to V5 so yeah bit late for that. Kind of nice for abandoned tools maybe to have websocket return just "4.9.1" without "-compat"

**Comment by oparada1988** [comment]
I got it working, but now I have other issues, I open a ticket for it #995

Thanks for everything!
